<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Admin Main Translation
    |--------------------------------------------------------------------------
    */

    'setting_and_profile' => 'настройка и профиль',
    'setting' => 'Параметр',
    'settings' => 'Настройки',

    // seo
    'settings_seo_metas' => 'SEO мета настройки',
    'seo_metas' => 'SEO мета',
    'seo_metas_home' => 'Домашняя страница',
    'seo_metas_search' => 'Страница поиска',
    'seo_metas_categories' => 'Страница категорий',
    'seo_metas_classes' => 'Страница со списком курсов',
    'seo_metas_login' => 'Страница авторизации',
    'seo_metas_register' => 'Страница регистрации',
    'seo_metas_about' => 'О странице',
    'seo_metas_contact' => 'Контактная страница',
    'seo_metas_blog' => 'Блог',
    'seo_metas_certificate_validation' => 'Проверка сертификата',

    // socials
    'settings_socials' => 'Настройки социальных сетей',
    'socials' => 'Социальные сети',

    // footer
    'settings_footer' => 'Настройки нижнего колонтитула',
    'footer' => 'Footer',
    'footer_first_column' => 'первый столбец',
    'footer_second_column' => 'второй столбец',
    'footer_third_column' => 'третья колонка',
    'footer_forth_column' => 'четвертая колонка',
    'item' => 'Предметы',
    'item_title' => 'Название элемента',
    'item_link' => 'Ссылка на товар',

    // main
    'main' => 'Главный',
    'home_sections' => 'Главная разделы',
    'settings_home_sections' => 'Настройка домашних разделов',
    'settings_main' => 'Основные параметры',
    'main_general' => 'Общий',
    'site_name' => 'Название сайта',
    'site_email' => 'Электронная почта сайтаSite email',
    'site_phone' => 'Телефон сайта',
    'site_language' => 'Язык сайта',
    'register_method' => 'Метод регистрации',
    'user_languages_lists' => 'Списки языков пользователя',
    'rtl_languages' => 'Языки RTL',
    'fav_icon' => 'Фавикон',
    'fav_icon_placeholder' => 'Отображается в браузере (48*48px)',
    'logo' => 'логотип',
    'logo_placeholder' => 'Отображается в шапке (55*55px)',
    'footer_logo' => 'логотип нижнего колонтитула',
    'footer_logo_placeholder' => 'Отображается в шапке (55*55px)',
    'rtl_layout' => 'RTL-макет',
    'preloading' => 'Предварительная загрузка',

    'main_financial' => 'финансовый',
    'courses_commission' => 'Комиссия курсов',
    'tax' => 'налог',
    'minimum_payout_amount' => 'Минимальная сумма выплаты',

    'main_payment' => 'Оплата',
    'currency' => 'Валюта',
    'gateways' => 'Шлюзы',
    'gateway_paypal' => 'Paypal',
    'gateway_payu' => 'Payu',
    'gateway_paytm' => 'Paytm',
    'gateway_paystack' => 'Платежная колода',

    'main_home_hero' => 'Раздел домашнего героя',
    'main_home_hero2' => 'Раздел домашнего героя 2',
    'home_hero' => 'Домашний герой',
    'home_hero2' => 'Домашний герой 2',
    'background' => 'Фон',
    'hero_background' => 'Предыстория героя',
    'hero_vector' => 'Вектор героя',
    'has_lottie' => 'Has Lottie',

    'main_page_background' => 'Фон страниц',
    'admin_login_background' => 'Фон входа в систему администратора',
    'admin_dashboard_background' => 'Фон панели администратора',
    'login_background' => 'Фон входа',
    'register_background' => 'История регистрации',
    'remember_pass_background' => 'Запомнить пароль Фон',
    'verification_background' => 'Фон проверки',
    'search_background' => 'Фон поиска',
    'categories_background' => 'Категории Фон',
    'become_instructor_background' => 'Стать инструктором',
    'certificate_validation_background' => 'Проверка сертификата',
    'blog_background' => 'История блога',
    'instructors_background' => 'История инструкторов',
    'dashboard_background' => 'Изображение приборной панели',
    'panel_sidebar_background' => 'Изображение боковой панели ',
    'user_avatar_background' => 'Аватар пользователя по умолчанию',
    'user_cover_background' => 'Пользовательская обложка по умолчанию',

    'custom_css_js' => 'Пользовательские css и js',
    'css' => 'Css',
    'js' => 'Js',

    'account_types' => 'Типы учетных записей',
    'add_account_types' => 'Добавить типы учетных записей',

    'site_bank_accounts' => 'Банковские счета сайта',
    'add_site_bank_accounts' => 'Добавить банковские счета',

    'report_reasons' => 'Сообщить о причинах',
    'add_report_reasons' => 'Добавить причины отчета',

    'notifications' => 'Уведомления',
    'notification_admin' => 'администратор',
    'notification_user' => 'пользователь',
    'notification_course' => 'курс',
    'notification_financial' => 'финансовый',
    'notification_sale_purchase' => 'продажа/покупка',
    'notification_plans' => 'планы',
    'notification_appointment' => 'встреча',
    'notification_quiz' => 'контрольный опрос',

    'notification_new_comment_admin' => 'админ нового комментария',
    'notification_support_message_admin' => 'поддержка сообщение админ',
    'notification_support_message_replied_admin' => 'на сообщение службы поддержки ответил администратор',
    'notification_promotion_plan_admin' => 'администратор плана продвижения',
    'notification_new_contact_message' => 'новое контактное сообщение',
    'notification_new_badge' => 'новый значок',
    'notification_change_user_group' => 'изменить группу пользователей',
    'notification_course_created' => 'созданный курс',
    'notification_course_approve' => 'одобрить курс',
    'notification_course_reject' => 'отклонение курса',
    'notification_new_comment' => 'новый комментарий',
    'notification_support_message' => 'сообщение службы поддержки',
    'notification_support_message_replied' => 'ответ на сообщение службы поддержки',
    'notification_new_rating' => 'новый рейтинг',
    'notification_webinar_reminder' => 'напоминание о вебинаре',
    'notification_new_financial_document' => 'новый финансовый документ',
    'notification_payout_request_admin' => 'администратор запроса на выплату',
    'notification_payout_request' => 'запрос на выплату',
    'notification_payout_proceed' => 'выплата продолжается',
    'notification_offline_payment_request' => 'запрос на автономный платеж',
    'notification_offline_payment_approved' => 'одобрен автономный платеж',
    'notification_offline_payment_rejected' => 'автономный платеж отклонен',
    'notification_new_sales' => 'новые продажи',
    'notification_new_purchase' => 'новая покупка',
    'notification_new_subscribe_plan' => 'новый план подписки',
    'notification_promotion_plan' => 'план продвижения по службе',
    'notification_new_appointment' => 'новое назначение',
    'notification_new_appointment_link' => 'ссылка на новую встречу',
    'notification_appointment_reminder' => 'напоминание о встрече',
    'notification_meeting_finished' => 'напоминание о встрече',
    'notification_new_certificate' => 'новый сертификат',
    'notification_waiting_quiz' => 'викторина в ожидании',
    'notification_waiting_quiz_result' => 'ожидание результата теста',

    'contact_us' => 'Контакт',
    'contact_us_edit' => 'Контактное редактирование',
    'contact_us_address' => 'Контактный адрес',
    'contact_us_phones' => 'Контактные телефоны',
    'contact_us_emails' => 'Контактные электронные письма',
    'contact_us_background' => 'Фон страницы контактов',
    'map_position' => 'Положение на карте',
    'map_zoom' => 'Масштабирование карты',
    'map_position_latitude' => 'Широта карты',
    'map_position_longitude' => 'Долгота на карте',
    'contact_us_phones_placeholder' => 'Разделите числа с помощью ,',
    'contact_us_emails_placeholder' => 'Разделите электронные письма с помощью ,',

    'error_404' => '404 страница',
    'error_404_image' => 'Изображение ошибки 404',
    'error_404_title' => '404 Заголовок ошибки',
    'error_404_description' => '404 Описание ошибки',

    'pages' => 'Страницы',
    'new_page' => 'Новая страница',
    'new_pages' => 'Новая Дополнительная Страница',
    'edit_pages' => 'редактировать страницу',
    'pages_name_placeholder' => 'название страницы в навигационной панели',
    'pages_order_placeholder' => 'порядок страниц в навигационной панели',
    'pages_lists_lead' => 'Список страниц. Вы можете отредактировать или удалить любую строку.',

    'latest_classes' => 'Последние курсы',
    'best_sellers' => 'Лучшие продавцы',
    'free_classes' => 'Бесплатные курсы',
    'discount_classes' => 'Курсы со скидкой',
    'best_rates' => 'Курсы с лучшим рейтингом',
    'trend_categories' => 'Раздел трендовых категорий',
    'testimonials' => 'Раздел отзывов',
    'subscribes' => 'Раздел подписчиков',
    'blog' => 'Раздел блога',
    'organizations' => 'Секция организаций',
    'instructors' => 'Секция инструкторов',
    'video_or_image_section' => 'Раздел видео или изображения',
    'main_home_video_or_image_box' => 'Раздел видео или изображений домашней страницы',

    'settings_navbar_links' => 'Настройки ссылок на панели навигации',
    'navbar_links' => 'Ссылки на навигационную панель',
    'top_navbar' => 'Верхняя панель навигации',
];
