<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Admin Users Translation
    |--------------------------------------------------------------------------
    */

    'users_list' => 'Users list',
    'user' => 'User',
    'user_or_instructor' => 'User or instructor',
    'users' => 'Users',
    'classes' => 'Курсы',
    'classes_sales' => 'Продажи курсов',
    'purchased_classes' => 'Приобретенные Курсы',
    'appointments' => 'Назначения',
    'appointments_sales' => 'Встречи продажи',
    'purchased_appointments' => 'Приобретенные встречи',
    'wallet_charge' => 'Плата за кошелек',
    'user_group' => 'Группа пользователей',
    'action' => 'Действие',
    'id' => 'ID',
    'name' => 'Имя',
    'instructors' => 'Инструкторы',
    'students' => 'Студенты',
    'role_name' => 'Имя роли',
    'admin_role' => 'Роль администратора',
    'full_name' => 'Полное имя',
    'status' => 'Статус',
    'users_count' => 'Количество пользователей',
    'page_lists_lead' => 'Список пользователей. Вы можете изменить или удалить любую строку.',
    'new_page_lead' => 'Вы можете создать нового пользователя.',
    'create_field_full_name_placeholder' => 'выберите имя.',
    'select_role' => 'выбрать роль.',
    'select_status' => 'выберите статус.',
    'create_field_email_placeholder' => 'example: m@m.m.',

    'search_user_or_instructor' => 'Поиск пользователя или преподавателя',

    /// admin users badges
    'select_badge' => 'Выберите значок',
    'badges' => 'Значки',
    'register_date' => 'Дата регистрации',
    'course_count' => 'Количество курсов',
    'course_rate' => 'Course rate',
    'sale_count' => 'Количество продаж',
    'support_rate' => 'Скорость поддержки',
    'condition' => 'Состояние',
    'condition_register_date' => 'день',
    'condition_course_count' => 'Курсы',
    'condition_course_rate' => 'Звезды',
    'condition_sale_count' => 'Продажи',
    'condition_support_rate' => 'Звезды',

    'groups' => 'Группы',
    'group_name' => 'Название группы',
    'users_groups' => 'Группы пользователей',
    'new_user_group' => 'Новая группа пользователей',

    'admin_users' => 'Пользователи',
    'admin_users_list' => 'Список пользователей',
    'admin_users_create' => 'Создать пользователей',
    'admin_users_edit' => 'Изменить пользователей',
    'admin_users_delete' => 'Удалить пользователей',
    'admin_users_badges' => 'Пользователи значков',

    'edit_page_title' => 'Изменить пользователя',
    'custom_badges' => '    ',
    'auto_badges' => 'Авто значки',

    'supports' => 'Поддерживать',
    'department' => 'Отделение',
  	'support_depatments' => 'Отделы поддержки',
    'new_department' => 'Новый отдел',
    'edit_department' => 'Изменить отдел',
    'departments' => 'Департаменты',

    'classes_conversations' => 'Беседы курса',
    'course_conversations' => 'Беседы курса',
    'course_conversations_lists_lead' => 'Список бесед пользователей и преподавателей',
    'support_conversation' => 'Поддержка разговора',
    'support_lists_lead' => 'Список бесед поддержки пользователей',
    'close_conversation' => 'Закрытый разговор',
    'open_attach' => 'Открыть вложение',
    'send_message_to' => 'отправить сообщение',
    'send_message_to_teacher' => 'отправить сообщение учителю',

    'user_avatar' => 'Аватар пользователя',
    'user_name' => 'Имя пользователя',
    'user_bio' => 'Биография пользователя',
    'rate' => 'Показатель',

    //new template notification
    'notifications' => 'Уведомления',
    'notification_single' => 'Один пользователь',
    'notification_all_users' => 'Все пользователи',
    'notification_students' => 'Все студенты',
    'notification_instructors' => 'Все инструкторы',
    'notification_organizations' => 'Все организации',
    'notification_group' => 'Конкретная группа',
    'notification_students_and_instructors' => 'Студенты и преподаватели',
    'mark_all_read' => 'Отметить все как прочитанное',
    'use_key_in_title_and_message_body' => 'Можно использовать эти ключи в заголовке и теле сообщения',

    'templates' => 'Шаблоны',
    'new_template' => 'Новый шаблон',
    'edit_template' => 'Изменить шаблон',
    'email' => 'Электронная почта пользователя',
    'mobile' => 'Мобильный телефон пользователя',
    'real_name' => 'Полное имя пользователя',
    'group_title' => 'Название группы пользователей',
    'badge_title' => 'Название значка',
    'financial_doc_desc' => 'Описание финансового документа',
    'financial_doc_type' => 'Тип финансового документа',
    'instructor_name' => 'Имя инструктора',
    'student_name' => 'Student name',
    'course_title' => 'Название курса',
    'quiz_title' => 'Название викторины',
    'quiz_result' => 'Результат викторины',
    'support_ticket_title' => 'Название обращения в службу поддержки',
    'contact_us_title' => 'Свяжитесь с нами',
    'time_and_date' => 'Время и дата',
    'link' => 'Ссылка',
    'rate_count' => 'Количество ставок',
    'amount' => 'количество',
    'payout_account' => 'Счет выплат',
    'subscribe_plan_name' => 'Название плана подписки',
    'promotion_plan_name' => 'Название плана продвижения',
    // .\

    'reject_request' => 'Отклонить запрос',
    'become_instructor_info' => 'стать инструктором информация',
    'become_instructors' => 'стать инструкторами',
    'instructor_requests' => 'Запросы инструктора',
    'accept_request' => 'Принять запрос',
    'check_user_information' => 'проверить информацию о пользователе',
    'become_instructors_list' => 'Стать инструктором запросы',
    'become_instructors_lists_page_lead' => 'Список запросов на получение статуса инструктора. Вы можете отредактировать или удалить любую строку.',

    'contacts' => 'Контакты',
    'contacts_lists' => 'Контактные сообщения',
    'contacts_message' => 'Контактное сообщение',

    'user_role_updated' => 'Роль пользователя изменилась.',
];
