<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Panel
    |--------------------------------------------------------------------------
    */

    'new_users' => 'Жаңы колдонуучулар',
    'user' => 'Колдонуучу',
    'users' => 'Колдонуучулар',
    'followers' => 'Жазылгандар',
    'following' => 'Жазылуу',
    'follow' => 'Жазылуу',
    'unfollow' => 'Жазылууну токтотуу',
    'webinars' => 'Курстар',
    'webinar' => 'Курс',
    'webinar_sales' => 'Жандуу сабак сатуулары',
    'content_sales' => 'Курс сатуулары',
    'my_webinars' => 'Менин курстарым',
    'you_not_have_any_webinar' => 'Эч бир курс жок!',
    'no_result_hint' => 'Биринчи курсуңузду түзүңүз жана башкалар сизден үйрөнсүн.',
    'choose_webinar' => 'Курсту тандоо',
    'certificates' => 'Сертификаттар',
    'quizzes' => 'Тесттер',
    'financial' => 'Финансылык',
    'requests' => 'Кайрылуу',
    'support' => 'Колдоо кызматы',
    'send_new_support' => 'Жаңы колдоо билдирүүсү',
    'notifications' => 'Билдирмелер',
    'settings' => 'Жөндөмдөр',
    'log_out' => 'Чыгуу',
    'create_a_class' => 'Курс жарыялоо',
    'create_a_webinar' => 'Курс жарыялоо',

    'invited_classes' => 'Чакырылган курстар',
    'invited_teacher' => 'Чакырылган инструктор',
    'invited_by' => 'Чакырды',
    'classes' => 'Курстар',
    'my_classes' => 'Менин курстарым',
    'my_activity' => 'Менин активдүүлүгүм',
    'download_sales' => 'Сатууларды жүктөп алыңыз',
    'course_sales' => 'Курстарды сатуу',
    'only_not_conducted_webinars' => 'Бир гана жандуу сабактар өткөрүлбөйт',
    'conducted' => 'Жүргүзүлгөн',
    'not_conducted' => 'Өткөрүлгөн эмес',

    'upcoming' => 'Алдыда',
    'start_learning' => 'Үйрөнүүнү баштаңыз',
    'my_purchases_no_result' => 'Сатып алынган курс жок!',
    'my_purchases_no_result_hint' => 'Мыкты инструкторлордон үйрөнүп, ырахат алыңыз...',

    'comment' => 'Комментарий',
    'comments' => 'Комментарийлер',
    'reply' => 'Жооп берүү',
    'replied' => 'Жооп берилген',
    'not_replied' => 'Жооп берилген эмес',
    'report' => 'Арыз',
    'report_success' => 'Сиздин арыз жөнөтүлдү.',
    'report_fail' => 'Арыз ишке ашкан жок. Системага киргенсизби?',
    'new_comments' => 'Жаңы комментарийлер',
    'my_class_comments' => 'Менин курсумдун комментарийлери',
    'my_comments' => 'Менин комментарийлерим',
    'comments_statistics' => 'Комментарийлердин статистикасы',
    'filter_comments' => 'Коммертарийлерди элеп алуу',
    'webinar_comments_list' => 'Курстун комментарийлеринин тизмеси',
    'comments_no_result' => 'Сизде эч кандай комментарий жок!',
    'comments_no_result_hint' => "Студент сиздин курстарыңызга комментарий бергенде, \n ал бул тизмеде пайда болот.",
    'my_comments_no_result' => 'Сиз эч кандай комментарий калтырган эмессиз!',
    'my_comments_no_result_hint' => "Сиздин комментарийлер жамааттын сапатын жакшыртууга жардам берет...",

    'my_purchases' => 'Мен сатып алгандар',
    'no_result_purchases' => 'Сатып алынган курс жок!',
    'no_result_purchases_hint' => 'Мыкты инструкторлордон үйрөнүп баштаңыз жана ырахат алыңыз...',
    'purchase_date' => 'Сатып алуу күнү',
    'purchased' => 'Сатып алынды',

    'favorites' => 'Тандалгандар',
    'favorite' => 'Тандалган',
    'favorite_live_classes' => 'Тандалган курстар',
    'no_result_favorites' => 'Тандалган курс жок!',
    'no_result_favorites_hint' => 'Сиз каалаган курсту тандалган курска кошуп, кийинчерээк каттала аласыз.',

    'meeting' => 'Жолугушуу',
    'meetings' => 'Жолугушуулар',
    'open_meetings' => 'Ачык жолугушуулар',
    'pending_appointments' => 'Күтүлүүчү жолугушуулар',
    'total_meetings' => 'Жалпы жолугушуулар',
    'amount' => 'Суммасы',
    'sales' => 'Сатуулар',
    'sales_amount' => 'Сатуулардын суммасы',
    'active_hours' => 'Активдүү сааттар',
    'meeting_statistics' => 'Жолугушуу статистикасы',
    'filter_meetings' => 'Жолугушууларды фильтрлөө',
    'meeting_list' => 'Жолугушуулар тизмеси',
    'meeting_requests_list' => 'Жолугушуу кайрылууларынын тизмеси',
    'show_only_open_meetings' => 'Ачык жолугушууларды гана көрсөтүү',
    'create_link' => 'Шилтеме түзүү',
    'contact_student' => 'Студент менен байланыш',
    'contact_instructor' => 'Инструктор менен байланышыңыз',
    'finish_meeting' => 'Жолугушууну бүтүрүү',
    'meeting_no_result' => 'Жолугушуу кайрылуусу жок!',
    'meeting_no_result_hint' => 'Резервге коюлган жолугушуулар бул тизмеде көрсөтүлөт.',
    'student_contact_information' => 'Студенттин байланыш маалыматы',
    'instructor_contact_information' => 'Инструктордун байланыш маалыматы',
    'my_timesheet' => 'Менин жадыбалым',
    'saturday' => 'Ишемби',
    'sunday' => 'Жекшемби',
    'monday' => 'Дүйшөмбү',
    'tuesday' => 'Шейшемби',
    'wednesday' => 'Шаршемби',
    'thursday' => 'Бейшемби',
    'friday' => 'Жума',
    'join_live_meeting' => 'Түз эфирдеги жолугушууга кошулуу',
    'add_live_meeting_link' => 'Жандуу жолугушуу шилтемесин кошуңуз',
    'add_live_meeting_link_success' => 'Жандуу жолугушуу шилтемеси ийгиликтүү кошулду',
    'add_live_meeting_link_fail' => 'Жандуу жолугушуу шилтемесин кошууда ката кетти',
    'add_live_meeting_link_hint' => 'Сиз Zoom, Bigbluebutton ж.б. шилтемелерди колдоно аласыз',
    'url' => 'URL',
    'my_hourly_charge' => 'Сааттык төлөм',
    'number_only' => 'Сандар гана...',
    'temporary_disable_meetings' => 'Жолугушууларды убактылуу өчүрүү',
    'success_temporary_disable_meetings' => 'Жолугушуулар ийгиликтүү өчүрүлдү.',
    'error_temporary_disable_meetings' => 'Жолугушуулар өчүрүлгөн жок.',
    'discount' => 'Эсептик чен',

    // dashboard
    'dashboard' => 'Куралдар тактасы',
    'i_not_available' => 'Оффлайн абалын жандыруу',
    'hi' => 'Салам',
    'have_event' => 'Сизде 5 жаңы иш-чара бар',
    'view_all_events' => 'Бардык иш-чараларды көрүү',
    'account_balance' => 'Эсеп балансы',
    'with_drawable' => 'Чечип алууга мүмкүн',
    'live_requests' => 'Жолугушуу кайрылуулары',
    'monthly_sales' => 'Айлык сатуулар',
    'learning_statistics' => 'Статистиканы карап чыгуу',
    'support_messages' => 'Колдоо кызматынын билдирүүлөрү',
    'next_badge' => 'Кийинки Белги',
    'noticeboard' => 'Билдирүү тактасы',
    'noticeboards' => 'Билдирүүлөр',
    'not_verified_alert' => 'Сиздин жекелик жана каржылык маалыматыңыз текшерилген жок, андыктан төлөм процессинин кечигишине алып келиши мүмкүн. Сураныч, аларды аныктаңыз: ',
    'this_link' => 'жөндөмөлөр',
    // Conversations
    'conversations' => 'Сүйлөшүүлөр',
    'create_support_message' => 'Жаңы колдоо билдирүүсү',
    'course_support' => 'Курстук колдоо',
    'course_type' => 'Курстун түрү',
    'platform_support' => 'Платформаны колдоо',
    'department' => 'Бөлүм',
    'attach' => 'Тиркеме',
    'attach_file' => 'Файлды тиркөө',
    'open_conversations' => 'Ачык сүйлөшүүлөр',
    'closed_conversations' => 'Жабык сүйлөшүүлөр',
    'total_conversations' => 'Жалпы сүйлөшүүлөр',
    'messages_history' => 'Билдирүүлөрдүн тарыхы',
    'support_summary' => 'Колдоо корутундусу',
  	'classes_support' => 'Курстарды колдоо',
  	'support_tickets' => 'Маселелер',
    'staff' => 'Кызматкерлер',
    'teacher' => 'Мугалим',
    'open' => 'Ачык',
    'closed' => 'Жабык',
    'close_request' => 'Кайрылууну жабуу',
    'reply_to_the_conversation' => 'Сүйлөшүүгө жооп бер',
    'support_no_result' => 'Сизде колдоо билдирүүлөрү жок',
    'support_no_result_hint' => 'Сиз инструкторлор менен же платформанын колдоо тобу менен байланыша аласыз.',

    'select_support' => 'Сүйлөшүүнү тандаңыз',
    'select_support_hint' => 'Сураныч, билдирүүлөрдүн таржымалын көрсөтүү үчүн колдоо сүйлөшүүсүн тандаңыз.',
    'message_filters' => 'Билдирүүлөрдү фильтрлөө',

    // notifications
    'notification_no_result' => 'Билдирмелер жок.',
    'notification_no_result_hint' => 'Ар бир маанилүү ишчара сизге билдирилет...',

    // comments
    'show_only_new_comments' => 'Жаңы комментарийлерди гана көрсөтүү',
    'reply_to_the_comment' => 'Комментарийге жооп бериңиз',
    'edit_comment' => 'Комментарийди өзгөртүү',

    //Marketing
    'marketing' => 'Маркетинг',
    'discounts' => 'Арзандатуулар',
    'create_a_new_discount' => 'Жаңы курс арзандатуу',
    'create_a_new_special_offer' => 'Жаңы өзгөчө сунуш түзүңүз',
    'show_only_active_discounts' => 'Активдүү арзандатууларды гана көрсөтүү',
    'discount_no_result' => 'Эч кандай арзандатуу жок...',
    'discount_no_result_hint' => 'Сиз арзандатууларды түзүп, сатууну көбөйтө аласыз.',
    'special_offers_no_result' => 'Арзандатуу жок...',
    'special_offers_no_result_hint' => 'Сиз курстарыңызга арзандатуу кошуп, сатууну көбөйтө аласыз.',

    'promotion' => 'Жарнама',
    'promotions' => 'Жарнамалар',
    'select_promotion_plan' => 'Жарнама планын тандаңыз',
    'promotions_history' => 'Жарнамалардын тарыхы',
    'promotion_days' => ':day күнгө',
    'select_course' => 'Курсту тандоо',
    'show_only_active_promotions' => 'Активдүү жарнамаларды гана көрсөтүү',
    'popular' => 'Популярдуу',
    'plan' => 'План',
    'pay' => 'Төлөө',
    'expired' => 'Мөөнөтү бүттү',
    'promote_the_webinar' => 'Курсту жайылтуу',
    'select_webinar_for_promotion' => 'Сураныч, жайылткыңыз келген курсту тандаңыз.',
    'promotion_no_result' => 'Жарнама жок!',
    'promotion_no_result_hint' => 'Жылдыруу пландарын активдештирүү менен сиз курстарыңыздын көрүүсүн жана сатууну көбөйтө аласыз.',

    // Instructors
    'filter_instructors' => 'Инструкторлорду фильтрлөө',
    'instructors_list' => 'Инструкторлор тизмеси',
    'add_an_instructor' => 'Жаңы инструктор',
    'instructors_no_result' => 'Азырынча инструктор кошулган жок!',
    'instructors_no_result_hint' => 'Сиз уюмга тиешелүү инструкторлорду түзө аласыз.',

    'filter_students' => 'Студенттерди фильтрлөө',
    'students_list' => 'Студенттер тизмеси',
    'add_an_student' => 'Жаңы студент',
    'students_no_result' => 'Азырынча студенттер кошулган жок!',
    'students_no_result_hint' => 'Уюмуңуздун студенттерин оңой эле кошо аласыз.',

    'meeting_sales' => 'Жолугушуу сатуулары',
    'appointment_sales' => 'Жолугушуу сатуулары',

    'bio' => 'Биография',
    'job_title' => 'Кызмат наамы',
    'bio_hint_1' => 'Профилдик картада аты-жөнүңүздүн ылдый жагында "Кызмат наамы" көрсөтүлөт.',
    'bio_hint_2' => 'Кыскача жазыңыз (2 же 3 сөз) Мисалы, "Продукциянын дизайнери, Сениор программдык инженери".',
    'interests_hint_1' => 'Кызыккан темаларды тандоо менен (инструкторлор үчүн) студенттерге жандуу жолугушууларды издөөдө сизди табууга жардам берет.',
    'interests_hint_2' => 'Эгер сиз жандуу жолугушууларды өткөрсөңүз, анда сунушталган так темаларды тандаңыз.',
    'not_assign_any_webinar' => 'Эч кандай курска байланган эмес',
    'active' => 'Активдүү',
    'inactive' => 'Активдүү эмес',
    'name' => 'Аты',
    'special_offers' => 'Атайын сунуштар',
    'special_offer' => 'Атайын сунуш',
    'show_only_active_special_offers' => 'Активдүү атайын сунуштарды гана көрсөтүү',

    'offline_title' => 'Оффлайн абалын жандыруу',
    'offline_message' => 'Оффлайн билдирүү',
    'offline_success' => 'Статусуңуз ийгиликтүү өзгөрдү!',
    'offline_hint' => 'Эгер сиз аккаунтуңузду оффлайн режимине койсоңуз, профилиңизде билдирүү пайда болот жана ал колдонуучуларга байкалат. Сиз төмөнкү киргизүүгө жекелештирилген билдирүүнү тере аласыз.',

    // months
    'month_1' => 'Үчт',
    'month_2' => 'Бир',
    'month_3' => 'Жал',
    'month_4' => 'Чын',
    'month_5' => 'Буг',
    'month_6' => 'Кул',
    'month_7' => 'Тек',
    'month_8' => 'Баш',
    'month_9' => 'Аяк',
    'month_10' => 'Тог',
    'month_11' => 'Жет',
    'month_12' => 'Беш',

    'user_setting_success' => 'Маалыматыңыз ийгиликтүү жаңыртылды',

    'remaining' => 'Калды',

    'organization_classes' => 'Уюмдун курстары',
    'filter_classes' => 'Курстарды фильтрлөө',
    'only_not_free_classes' => 'Жалаң акы төлөнүүчү курстар',
    'only_free_classes' => 'Бир гана бекер курстар',

    'new_noticeboard' => 'Жаңы билдирүү',
    'noticeboard_success_send' => 'Жаңы билдирүү ийгиликтүү жөнөтүлдү',
    'noticeboard_success_send_to' => 'Жаңы билдирме тактасы :users_count колдонуучуга ийгиликтүү жөнөтүлдү',

    'more_info' => 'Көбүрөөк маалымат',
  	'partner_instructor_hint' => 'Өнөктөш инструктор курстун мазмунуна кире алат жана алардын профили курстун бетинде көрсөтүлөт.',
  	
  	'affiliate' => 'Өнөктөш',
    'affiliates' => 'Өнөктөш',
    'affiliates_page' => 'Өнөктөш маркетинг',
    'affiliate_statistics' => 'Өнөктөш Статистикасы',
    'affiliate_summary' => 'Өнөктөш Корутундусу',
    'earnings' => 'Кирешелер',
    'referred_users' => 'Чакырылган колдонуучулар',
    'registration_bonus' => 'Катталуу үчүн бонустар',
    'affiliate_bonus' => 'Сатуулар комиссиясы',
    'registration_date' => 'Катталуу датасы',
    'user_registration_reward' => 'Ар бир чакырылган колдонуучунун катталуусунан түшкөн кирешеңиз',
    'referred_user_purchase_commission' => 'Чакырылган колдонуучунун сатып алууларынан сизге түшкөн комиссия',
    'referred_user_registration_reward' => 'Сиздин өнөктөштүк кодуңуз менен регистрация болгон чакырылган колдонуучунун кирешеси',
    'your_affiliate_code' => 'Сиздин өнөктөштүк кодуңуз',
    'affiliate_url' => 'Сиздин өнөктөштүк URL',
	'content_defined' => 'Мазмун аныкталган',
  	'purchased_courses' => 'Сатып алынган курстар',
];
