<?php

return [

    /*
    |--------------------------------------------------------------------------
    | General Translations
    |--------------------------------------------------------------------------
    */

    'title' => 'Аталышы',
    'sub_title' => 'Субтитр',
    'name' => 'Аты',
    'seo_description' => 'SEO-мета-сүрөттөмө',
    'cover_image' => 'Мукаба сүрөтү',
    'thumbnail_image' => 'Эскиз',
    'image' => 'Сүрөт',
  	'images' => 'Сүрөттөр',
    'demo_video' => 'Демо видео',
    'optional' => 'Кошумча',
    'description' => 'Сүрөттөмө',
    'summary' => 'Корутунду',
    'study_time' => 'Окуу убактысы',
    'date_time' => 'Датасы/Убактысы',
    'availability_times' => 'Жеткиликтүү убакыттар',
    'available' => 'Жеткиликтүү',
    'available_for_meetings' => 'Жолугушуулар үчүн жеткиликтүү',
    'meeting' => 'Жолугушуу',
    'meetings' => 'Жолугушуулар',
    'link' => 'Шилтеме',
    'duration' => 'Узактыгы',
    'minutes' => 'Мүнөттөр',
    'min' => 'Мин',
    'view' => 'Көрүү',
    'view_profile' => 'Профильди көрүү',
    'review_or_edit' => 'Карап чыгуу/Өзгөртүү',
    'review' => 'Карап чыгуу',
    'invited' => 'Чакырылган',
    'try_again' => 'Кайра аракет кыл',
    'you_can_try_again' => 'Кабатыр болбоңуз, кайра аракет кылсаңыз болот.',
    'start' => 'Баштоо',
    'volume' => 'Үндүн көлөмү',
    'file_type' => 'Файлдын типи',
    'accessibility' => 'Жеткиликтүүлүк',
    'choose_accessibility' => 'Акысызбы же акы төлөнүүчүбү??',
    'attachments' => 'Тиркемелер',
    'choose_attachments' => 'Сабак тиркемелери катары тиешелүү файлдарды тандаңыз',
    'paid' => 'Төлөндү',
    'paid_amount' => 'Төлөнгөн сумма',
    'instructor' => 'Инструктор',
    'instructors' => 'Инструкторлор',
    'students' => 'Студенттер',
    'students_and_instructors' => 'Студенттер жана Инструкторлор',
    'search_instructors' => 'Инструкторду издөө...',
    'publish_date' => 'Жарыланган датасы',
    'forced' => 'Мажбур',
    'yes' => 'Ооба',
    'no' => 'Жок',

    'course_sessions' => 'Класс сессиялары',
    'previous_lesson' => 'Мурунку сабак',
    'next_lesson' => 'Кийинки сабак',

    'drag_to_change_order' => 'Тартипти өзгөртүү үчүн сүйрөңүз',

    'controls' => 'Аракеттер',
    'phone' => 'Телефон',
    'mobile' => 'Телефон',
    'email' => 'Email',

    'add_time' => 'Убакыт кош',
    'clear_all' => 'Баарын тазала',
    'additional_information' => 'Кошумча маалымат',
    'capacity' => 'Кубаттуулугу',
    'start_date' => 'Башталыш күнү',
    'time' => 'Убакыт',
    'date' => 'Дата',
    'date_created' => 'Түзүлгөн датасы',
    'partner_instructor' => 'Өнөктөш инструктор',
    'subscribe' => 'Жазылуу',
    'add_to_cart' => 'Корзинага кошуу',
    'add_to_calendar' => 'Календарга кошуу',
    'add_to' => 'Кошуу',
    'reminder' => 'Эскерткич',
    'calendar' => 'Календарь',
    'price' => 'Баасы',
    '0_for_free' => 'Акысыз болсо 0 деп жазыңыз',
    'free' => 'Акысыз',
    'enroll_on_webinar' => 'Курска катталуу',
    'free_meetings' => 'Акысыз жолугушуулар',
    'select_a_partner_teacher' => 'Өнөктөш инструкторду тандаңыз',
    'select_a_teacher' => 'Инструкторду тандаңыз',
    'choose_instructor' => 'Инструкторду тандаңыз',
    'search' => 'Издөө',
    'search_instructor' => 'Окутуучунун атын, электрондук почтасын же телефонун изде',
    'search_user' => 'Колдонуучуну издөө',
    'tags' => 'Тегдер',
    'type_tag_name_and_press_enter' => 'Тег атын териңиз жана enter баскычын басыңыз',
    'moderator_password' => 'Модератордун сырсөзү',

    'category' => 'Категория',
    'choose_category' => 'Категорияны тандаңыз',
    'category_filters' => 'Категория фильтрлери',
    'tickets' => 'Маселелер',
    'add_ticket' => 'Жаңы баа планы',
    'add_plan' => 'Жаңы план',
    'add_new_ticket' => 'Жаңы баа планы',
    'discount' => 'Арзандатуу',
    'ticket_no_result' => 'Баа планы жок!',
    'ticket_no_result_hint' => 'Баа пландарын түзүү менен сиз курсуңузга убакыт жана кубаттуулукка жараша бааларды кошо аласыз.',

    'edit' => 'Өзгөртүү',
    'delete' => 'Өчүрүү',
    'remove' => 'Алып салуу',

    'list' => 'Тизме',
    'reservation' => 'Резерв',
    'my_reservation' => 'Менин резервдерим',
    'result' => 'Жыйынтык',
    'results' => 'Жыйынтыктар',
    'my_results' => 'Менин жыйынтыктарым',

    'all' => 'Бардыгы',
    'sessions' => 'Сессиялар',
    'add_session' => 'Жаңы сессия',
    'add_new_sessions' => 'Жаңы жандуу сессия',
    'sessions_no_result' => 'Жандуу сессиялар жок!',
    'sessions_no_result_hint' => 'Студенттер кошулуп, үйрөнө башташы үчүн жандуу сессияларды түзө аласыз.',
    'create_join_link' => 'Кошулуу шилтемесин түзүү',

    'newest' => 'Эң жаңы',
    'expensive' => 'Эң жогорку баа',
    'inexpensive' => 'Эң төмөн баа',
    'bestsellers' => 'Эң көп сатылгандар',
    'best_rates' => 'Эң жакшы баалангандар',

    'files' => 'Файлдар',
    'file' => 'Файл',
    'source' => 'Булак',
    'add_files' => 'Жаңы файл',
    'add_new_files' => 'Жаңы файл кошуу',
    'files_no_result' => 'Эч кандай файл аныкталган эмес!',
    'files_no_result_hint' => 'Сиз курстун видео бөлүктөрүн, долбоорлорду, тиркемелерди жана көнүгүүлөрдү файл катары көрсөтүп бере аласыз.',

    'test_lesson' => 'Текст сабагы',
    'lesson' => 'Сабак',
    'add_test_lesson' => 'Жаңы текст сабагы',
    'add_new_test_lesson' => 'Жаңы текст сабагын кошуу',
    'text_lesson_no_result' => 'Текст сабагы жок!',
    'text_lesson_no_result_hint' => 'Студенттер аларга катталып, үйрөнө башташы үчүн тексттик сабактарды түзүңүз.',

    'prerequisites' => 'Пререквизиттер',
    'add_prerequisites' => 'Жаңы Пререквизит',
    'add_new_prerequisites' => 'Жаңы пререквизит кошуу',
    'select_prerequisites' => 'Пререквизитти тандоо',
    'search_prerequisites' => 'Пререквизиттердии издөө',
    'prerequisites_no_result' => 'Эч кандай пререквизит көрсөтүлгөн эмес!',
    'prerequisites_no_result_hint' => 'Сиз студенттердин жакшыраак үйрөнүшү үчүн талап кылынган же сунушталган пререквизиттерди түзө аласыз.',

    'basic_information' => 'Негизги маалымат',
    'extra_information' => 'Кошумча маалымат',
    'pricing' => 'Баасы',
    'content' => 'Мазмуну',

    'faq' => 'Көп берилүүчү суроолор',
    'add_faq' => 'Жаңы көп берилүүчү суроо',
    'answer' => 'Жооп',
    'answers' => 'Жооптор',
    'view_answers' => 'Жоопторду көрүү',
    'faq_no_result' => 'Бир дагы көп берилүүчү суроолор жок!',
    'faq_no_result_hint' => 'Көп берилүүчү суроолорду түзүү менен сиз колдонуучуларга курсуңуз жөнүндө көбүрөөк билүүгө жардам бересиз.',

    'quiz_certificate' => 'Тесттер & Сертификаттоо',
    'certificate' => 'Сертификат',
    'certificate_id' => 'Сертификат ID',
    'certificate_and_documents' => 'Сертификаттар & Документтер',
    'add_quiz' => 'Жаңы тест',
    'add_new_quizzes' => 'Жаңы тест',
    'select_a_quiz' => 'Тестти танда',
    'quiz' => 'Тест',
    'questions' => 'Суроолор',
    'total_mark' => 'Жалпы упай',
    'pass_mark' => 'Босого упай',
    'mark' => 'Упай',
    'not_participated' => 'Катышкан эмес',
    'dont_have_quiz' => 'Сизде тест жок, тестти аныктаңыз',
    'quizzes_no_result' => 'Бул курс үчүн тест тандалган эмес.',
    'quizzes_no_result_hint' => 'Тесттерди түзүү менен сиз студенттерге баа берип, аларга сертификаттарды тапшыра аласыз.',

    'agree_rules' => 'Мен шарттар & эрежелер менен макулмун.',

    'message_to_reviewer' => 'Текшерүүчүгө билдирүү жазуу',

    'send_for_review' => 'Карап чыгууга жөнөтүү',
    'save_as_draft' => 'Сомо катары сактоо',
    'draft' => 'Сомо',
    'waiting' => 'Күтүүдө',
    'done' => 'Бүттү',
    'reject' => 'Четке кагуу',
    'rejected' => 'Четке кагылды',

    'close' => 'Жабуу',
    'save' => 'Сактоо',
    'continue' => 'Улантуу',
    'submit' => 'Сактуу',
    'new' => 'Жаңы',
    'history' => 'Тарых',
    'item_id' => 'Продукттун ID\'си',
    'export_list' => 'Студенттердин тизмесин экспорттоо',
    'duplicate' => 'Дубликаттоо',

    'updated_at' => 'Жаңыртылган дата',
    'from' => 'Баштап',
    'to' => 'Чейин',
    'show_results' => 'Жыйынтыктарды көрсөтүү',
    'status' => 'Статус',
    'published' => 'Жарыяланган',
    'type' => 'Тип',
    'active' => 'Активдүү',
    'verified' => 'Текшерилди',
    'not_verified' => 'Текшерилген жок',
    'inactive' => 'Активдүү эмес',
    'disabled' => 'Өчүрүлгөн',
    'disable' => 'Өчүрүү',
    'open' => 'Ачуу',
    'invoice' => 'Эсеп-фактура',
    'feedback' => 'Пикир',
    'by' => 'Аркылуу',
    'finish' => 'Бүтүрүү',
    'finished' => 'Бүттү',
    'pending' => 'Күтүлүүдө',
    'selected' => 'Тандалды',
    'select' => 'Тандалды',
    'required' => 'Талап кылынат',
    'not_bought' => 'Сатып алынган эмес!',
    'not_access' => 'Кирүү четке кагылды!',
    'not_access_to_this_content' => 'Бул мазмунга кирүү мүмкүнчүлүгүңүз жок!',
    'play' => 'Ойнотуу',
    'play_online' => 'Ойнотуу (Стрим)',
    'read' => 'Окуу',

    'are_you_sure' => 'Ишенимдүүсүзбү?',
    'deleteAlertHint' => "Бул аракетти артка кайтаруу мүмкүн эмес!",
    'deleteAlertConfirm' => 'Өчүрүү',
    'deleteAlertFailHint' => 'Өчүрүүдө ката кетти!',
    'deleteAlertSuccessHint' => 'Продукт ийгиликтүү өчүрүлдү.',
    'cancel' => 'Жокко чыгаруу',
    'canceled' => 'Жокко чыгарылды',
    'success' => 'Ийгиликтүү',
    'fail' => 'Ийгиликсиз',

    'unavailable' => 'Жеткиликсиз',
    'unavailable_description' => 'Жеткиликсиздик билдирүүсү',

    'not_defined' => 'Аныкталган эмес',

    'days' => 'Күн',
    'day' => 'Күн',
    'hr' => 'Саат',
    'sec' => 'Секунд',
    'off' => 'Арзандатуу',
    'offer' => ':off% Сунуш',

    'sort_by' => 'Сорттоо',
    'in' => 'Ичинде',
    'created_by' => 'Тарабынан түзүлдү',
    'created_at' => 'Түзүлгөн датасы',
    'created' => 'Түзүлдү',
    'create' => 'Түзүү',
    'save_change' => 'Сактоо',
    'ratings' => 'Рейтингдер',

    'share' => 'Бөлүшүү',
    'share_this_course_with_others' => 'Курсту досторуңуз менен бөлүшүңүз',
    'profile' => 'Профиль',
    'telegram' => 'Telegram',
    'facebook' => 'Facebook',
    'whatsapp' => 'Whatsapp',
    'twitter' => 'Twitter',
    'book_a_meeting' => 'Жолугушууга жазылыңыз',
    'author_posts' => 'Автордук посттор',
    'reserve_a_meeting' => 'Жолугушууну резервке коюу',
    'go_to_class' => 'Курска баруу',
    'go_to_settings' => 'Жөндөөлөргө өтүү',
    'course_page_title' => 'Курс',

    'duplicate_review_for_webinar' => 'Курс үчүн кайталанган кароо',
    'creator' => 'Түзүүчү',
    'manual' => 'Кол менен',
    'automatic' => 'Автоматтык',
    'start_payment' => 'Төлөмдү баштоо',
    'pay' => 'Төлөө',
    'saturday' => 'Ишемби',
    'sunday' => 'Жекшемби',
    'monday' => 'Дүйшөмбү',
    'tuesday' => 'Шейшемби',
    'wednesday' => 'Шаршемби',
    'thursday' => 'Бейшемди',
    'friday' => 'Жума',
    'all_days' => 'Бардык күндөр',

    'my_panel' => 'Менин панелим',
    'my_profile' => 'Менин профилим',
    'user_profille_page_title' => 'Колдонуучунун профили',
    'edit_selected_image' => 'Тандалган сүрөттү кесип ал',

    'request_failed' => 'Кайрылуу ишке ашкан жок',
    'request_success' => 'Кайрылуу ийгиликтүү аткарылды!',

    'cart_page_title' => 'Корзина',
    'checkout_page_title' => 'Сатып алуу',
    'channel_payment_disabled' => 'Төлөм шлюзи өчүрүлгөн.',
    'income_los_then_minimum_payout' => 'Сиздин кирешеңиз минималдуу төлөм суммасынан азыраак. Чектөөдөн өтүү үчүн күтө туруңуз.',

    'paid_form_online_payment' => 'Онлайн төлөм',
    'paid_form_credit' => 'Paid form Credit',
    'paid_for_sale' => 'Paid for Sale',
    'tax_get_form_buyer' => 'Tax form Buyer',
    'income_sale' => 'Income Sale',
    'paid_for_commission' => 'Paid for Commission',
    'get_commission_from_seller' => 'Commission from Seller',
    'refund_money_to_buyer' => 'Refunded to Buyer',
    'refund_tax' => 'Refunded Tax',
    'refund_commission_to_seller' => 'Refunded Commission to Seller',
    'refund_commission' => 'Refunded Commission',
    'refund_income' => 'Refunded Income',
    'charge_account' => 'Charge Account',
    'withdraw_account' => 'Withdraw Account',
    'income_for_subscribe' => 'Income for Subscribe',
    'paid_form_subscribe' => 'Paid for Subscribe',
    'income_for_promotion' => 'Paid for Promotion',

    'ticket_for_students_until_date' => 'Биринчи :students студент үчүн :date чейин',
    'ticket_until_date' => ':date чейин',

    'about' => 'Сиз жөнүндө',
    'educations' => 'Билими',
    'experiences' => 'Тажрыйба',
    'occupations' => 'Чебер темалары',
    'identity_and_financial' => 'Күбөлүк & Финансылык',

    'copy' => 'Көчүрүү',
    'copied' => 'Көчүрүлдү',
    'user_role' => 'Колдонуучу тиби',
    'all_roles' => 'Бардык типтер',

    'error_404_page_title' => 'Барак табылган жок',
    'i_passed_this_lesson' => 'Мен бул сабактан өттүм',
    'course_learning_change_status_success' => 'Окуу статусуңуз ийгиликтүү өзгөрдү.',
    'course_learning_change_status_error' => 'Окуу статусу өзгөргөн жок.',
    'course_learning_passed' => 'Курстун :percent% ы өттү.',

    'not_login_toast_lang' => 'Чектелген мазмун',
    'not_login_toast_msg_lang' => 'Сураныч, мазмунга кирүү үчүн кириңиз.',
    'not_access_toast_lang' => 'Кирүү четке кагылды',
    'not_access_toast_msg_lang' => 'Бул мазмунга кирүү мүмкүнчүлүгүңүз жок.',
    'can_not_try_again_quiz_toast_lang' => 'Reched out',
    'can_not_try_again_quiz_toast_msg_lang' => 'Бул тестти кайра тапшыра албайсыз.',
    'can_not_download_certificate_toast_lang' => 'Жүктөп алуу ишке ашкан жок',
    'can_not_download_certificate_toast_msg_lang' => 'Бул сертификатты жүктөй албайсыз.',
    'session_finished_toast_title_lang' => 'Сессия аяктады',
    'session_finished_toast_msg_lang' => 'Сиз өтө кеч калып калдыңыз, бул сессия бүттү',

    'zoom_api' => 'Zoom API',
    'zoom_jwt_token' => 'Zoom JWT Token',
 	'how_zoom_jwt_token' => 'Zoom JWT Token кантип түзүүгө болот',
    'instructor_is_not_available' => 'Инструктор убактылуу жеткиликсиз.',
  
    'chapter' => 'Бөлүм',
    'chapters' => 'Бөлүмдөр',
    'add_new_chapter' => 'Жаңы бөлүм кошуу',
    'new_chapter' => 'Жаңы бөлүм',
    'edit_chapter' => 'Бөлүмдү түзөтүү',
    'chapter_title' => 'Бөлүмдүн аталышы',
    'topic' => 'Тема',
    'parts' => 'Бөлүктөр',
  	'content_defined' => 'Мазмуну аныкталды',
    'no_chapter' => 'Бөлүм жок',
  	'add_file' => 'Файл кошуу',
];
