<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Admin General Translations
    |--------------------------------------------------------------------------
    */

// General | Side Menu | Buttons
  
    'crm' => 'CRM',
    'content' => 'Содержание',
    'lists' => 'Список',
    'list' => 'Список',
    'new' => 'Новое',
    'new_ticket' => 'Новый запрос в Службу поддержки',
    'tickets' => 'билеты',
    'create' => 'Создавать',
    'name' => 'Имя',
    'item' => 'Предмет',
    'user_name' => 'Имя пользователя',
    'title' => 'Загалавок',
    'link' => 'URL-адрес',
    'admin' => 'Администратор',
    'min' => ' Минута',
    'choose_title' => 'Загалавок',
    'choose_category' => 'Выберите категорию',
    'caption' => 'Подпись',
    'actions' => 'Действия',
    'action' => 'Действие',
    'status' => 'Статус',
    'all_status' => 'Все Статусы',
    'logout' => 'Выход из системы',
    'show_website' => 'Показать Веб-сайт',
    'type' => 'Тип',
    'types' => 'Тип',
    'all_types' => 'Все Типы',
    'sort' => 'Сортировать',
    'edit' => 'Редактировать',
    'check' => 'Проверять',
    'search' => 'Поиск',
    'reply' => 'Ответить',
    'replied' => 'Ответил',
    'conversation' => 'Разговор',
    'conversations' => 'Разговоры',
    'with' => 'с',
    'login' => 'Авторизоваться',
    'email' => 'Электронная почта',
    'id' => 'ID',
    'mobile' => 'Мобильный',
    'sms' => 'смс',
    'phone' => 'Телефон',
    'bio' => 'Био',
    'ban' => 'Запрет',
    'unpublish' => 'Неопубликованный',
    'unpublished' => 'Неопубликованный',
    'publish' => 'Публиковать',
    'published' => 'Опубликованный',
    'hidden' => 'Скрытый',
    'pending' => 'Ожидаемый',
    'waiting' => 'Ожидание',
    'accepted' => 'Принято',
    'open' => 'Открыть',
    'close' => 'Закрывать',
    'pending_reply' => 'Ожидающий Ответа',
    'show' => 'Покажите',
    'all' => 'Все',
    'password' => 'Пароль',
    'delete' => 'Удалить',
    'select' => 'Выбрать',
    'submit' => 'Сохранить',
    'subject' => 'Загалавок',
    'approved' => 'Одобренный',
    'reject' => 'Отклонять',
    'rejected' => 'Отклоненный',
    'optional' => 'Необязательный',
    'days' => 'Дни',
    'view_all' => 'Просмотреть Все',
    'message' => 'Сообщение',
    'send' => 'Отправить',
    'sender' => 'Отправитель',
    'send_noticeboard' => 'Отправить уведомление',
    'noticeboard' => 'Доска объявлений',
    'save_change' => 'сохранить изменения',
    'save' => 'Сохранить',
    'save_and_publish' => 'Сохранение и публикация',
    'save_and_continue' => 'Сохранить и продолжить',
    'yes' => 'Да',
    'no' => 'Нет',
    'max' => 'Макс',
    'to' => 'К',
    'from' => 'От',
    'total' => 'Весь',
    'active' => 'Активный',
    'is_draft' => 'Проект',
    'draft' => 'Проект',
    'disable' => 'Отключать',
    'add_new' => 'Добавить Новый',
    'inactive' => 'Неактивный',
    'cancel' => 'Отменить',
    'created_at' => 'Дата Создания',
    'updated_at' => 'Дата Обновления',
    'add' => 'Добавь',
    'remove' => 'Удалять',
    'category' => 'Категория',
    'all_categories' => 'Все Категории',
    'all_users' => 'Все пользователи',
    'user' => 'Пользователь',
    'read' => 'Прочитай',
    'unread' => 'Непрочитанный',
    'reviews' => 'Обзоры',
    'last_update' => 'Последнее обновление',
    'default_commission' => 'Ставка Комиссии По Умолчанию',
    'created_date' => 'Дата Создания',
    'delete_confirm_msg' => 'Ты уверен? | Вы хотите продолжить?',
    'view_rates_details' => 'Подробная информация о рейтинге',
    'show_results' => 'Показывать результаты',
    'export_xls' => 'Экспорт Excel',
    'filter_items' => 'Фильтровать элементы',
    'items' => 'Предмет',
    'filter_type' => 'Тип фильтра',
    'course' => 'Курс',
    'courses' => 'Курсы',
    'print' => 'Печать',
    'order' => 'Заказ',
    'attach' => 'Прикреплять',
    'avatar' => 'Изображение профиля',
    'avatar_hint' => 'Удалите путь "/store/number/" из начала ссылки после выбора файла.',
    'icon' => 'Иконка',
    'image' => 'Изображение',
    'cover_image' => 'Изображение на обложке',
    'bestsellers' => 'Лучшие продавцы',
    'newest' => 'Новейший',
    'oldest' => 'Старейший',
    'marketing' => 'Маркетинг',
    'advertising' => 'Рекламирующий',
    'advertising_banners' => 'Рекламные Баннеры',
    'ad_banners' => 'Реклама. Баннеры',
    'advertising_banners_list' => 'Рекламные Баннеры',
    'banners' => 'Баннеры',
    'banner_size' => 'Размер баннера',
    'new_banner' => 'Новый Баннер',
    'position' => 'Позиция',
    'promotion_sales' => 'Рекламные продажи',
    'content_promotion' => 'Продвижение контента',
    'newsletters' => 'Рассылка по электронной почте',

//Meetings

    'consultant' => 'Консультант',
    'consultants' => 'Консультанты',
    'reservatore' => 'Резервный',
    'total_reservatores' => 'Всего Резерваций',
    'cost' => 'Сумма',
    'time' => 'Время',
    'date' => 'Дата',
    'join_appointment' => 'Совместное заседание',
    'Url' => 'URL-АДРЕС',
    'join' => 'Присоединяйтесь',
    'join_link' => 'URL-АДРЕС для присоединения',
    'send_appointment_reminder' => 'Отправить напоминание',
    'send_reminder' => 'Отправить напоминание',
    'remind_title' => 'Название напоминания:',
    'remind_message' => 'Сообщение с напоминанием:',
    'unavailable' => 'Недоступный',
    'available' => 'Доступный',
    'pending_appointments' => 'Предстоящие заседания',

//Blog

    'blog' => 'Блог',
  	'posts' => 'Посты',
    'blog_categories' => 'Категории блогов',
    'create_category' => 'Новая категория',
    'author' => 'Автор',
    'all_authors' => 'Все авторы',
    'create_blog' => 'Новая Запись в Блоге',
    'new_post' => 'Новый Пост',
    'edit_blog' => 'Редактировать Пост в Блоге',
    'comments_section' => 'Включить комментарии',

//Categories

    'categories_list_page_title' => 'Список категорий',
    'categories' => 'Категории',
    'tags_count' => 'Теги',
    'new_page_lead' => 'Вы можете создать новую категорию.',
    'parent_name' => 'Родитель',
    'select_parent_name' => 'Написать родительский заголовок',
    'categories_count' => 'Категории',
    'trends_lists_lead' => 'Список категорий трендов. Вы можете отредактировать или удалить любую строку.',
    'sub_category' => 'Подкатегория',
    'has_sub_category' => 'Включает Подкатегории',
    'add_sub_categories' => 'Добавление подкатегорий',
    'admin_categories' => 'Категории',
    'admin_categories_list' => 'Список категорий',
    'admin_categories_create' => 'Категории Создают',
    'admin_categories_edit' => 'Категории Редактировать',
    'admin_categories_delete' => 'Категории Удалить',
    'trends' => 'Тенденции',
    'new_trend' => 'Новая Тенденция',
    'trend_icon' => 'Икона',
    'trend_color' => 'Цвет фона',
    'trend_color_placeholder' => 'Пример: #3dbca7 or rgb(0,0,0)',
    'create_trend_category' => 'Новая категория Трендов',

//Certificate

    'certificate_list_page_title' => 'Список сертификатов',
    'certificate' => 'Сертификат',
  	'certificate_id' => 'ID Cертификата',
    'certificate_count' => 'Сертификаты',
    'sub_certificate' => 'Субсертификат',
    'has_sub_certificate' => 'Включает в себя дополнительный сертификат',
    'add_sub_certificate' => 'Новый субсертификат',
    'admin_certificate' => 'Сертификат',
    'admin_certificate_list' => 'Список сертификатов',
    'admin_certificate_create' => 'Сертификаты Создают',
    'admin_certificate_edit' => 'Сертификаты Редактировать',
    'admin_certificate_delete' => 'Удаление сертификатов',
    'certificate_templates_list_page_title' => 'Шаблоны сертификатов',
    'certificate_new_template_page_title' => 'Новый Шаблон Сертификата',
    'certificate_template_edit_page_title' => 'Редактировать шаблон сертификата',

//Comments

    'classes_comments' => 'Комментарии к курсу',
    'blog_comments' => 'Комментарии в блоге',
    'comments' => 'Комментарии',
    'comment' => 'Комментарий',
    'post' => 'Пост',
    'post_or_webinar' => 'Страница',
    'enable_comments' => 'Включить комментарии',
    'publish_item' => 'Опубликовать элемент',
    'content_placeholder' => 'Основной контент',
    'description_placeholder' => 'Напишите краткое описание',
    'main_comment' => 'Основной комментарий',
    'reply_comment' => 'Ответ на комментарий',
    'reply_comments' => 'Отвечать на комментарии',
    'reply_list' => 'Список ответов',
    'edit_comment' => 'Редактировать Комментарий',
    'reports' => 'Отчеты',
    'classes_comments_reports' => 'Комментарии к курсу',
    'classes_reports' => 'Отчеты о курсах',
    'blog_comments_reports' => 'Комментарии в блоге',
    'comments_reports' => 'Отчеты о комментариях',
    'reported_comment' => 'Сообщенный комментарий',
    'report_detail' => 'Подробности отчета',
    'report_message' => 'Сообщение об отчете',
    'testimonials' => 'Рекомендации',
    'new_testimonial' => 'Новый Отзыв',
    'edit_testimonial' => 'Редактировать Отзыв',
    'testimonial_user_avatar_placeholder' => 'Оставьте его пустым, чтобы загрузить изображение профиля по умолчанию.',
    'testimonial_rate_placeholder' => 'Только цифры (от 0 до 5)',

//Dashboard

    'dashboard' => 'Приборная панель',
    'admin_dashboard_show' => 'Показать панель мониторинга',
    'welcome' => 'Добро пожаловать',
    'welcome_card_text' => 'Все находится под вашим контролем, используйте кнопки быстрого доступа, чтобы легко управлять соответствующими действиями.',
    'clear_all_cache' => 'Очистить кэш',
    'daily_sales_type_statistics' => 'Тип курса Ежедневные Продажи',
    'today_sales' => 'Сегодняшние продажи',
    'income_statistics' => 'Доход от платформы',
    'today' => 'Сегодня',
    'this_month' => 'Месяц',
    'this_year' => 'Год',
    'total_incomes' => 'Общий Доход',
  	'salescount' => 'Количество продаж',
    'total_sales_statistics' => 'Общая Статистика продаж',
    'new_sale' => 'Новая Распродажа',
    'new_comment' => 'Новый комментарий',
    'pending_review' => 'Ожидающий рассмотрения',
  	'pending_review_classes' => 'Ожидающие рассмотрения Курсы',
    'sales_statistics' => 'Статистика продаж',
    'month' => 'Месяц',
    'year' => 'Год',
    'recent_comments' => 'Последние комментарии',
    'recent_tickets' => 'Последние обращения в службу поддержки',
    'recent_live_classes' => 'Недавние Живые Занятия',
    'recent_courses' => 'Последние курсы',
    'new_registration_statistics' => 'Статистика регистрации Пользователей',
    'today_income' => 'Сегодняшняя Прибыль',
    'week_income' => 'Недельная Прибыль',
    'month_income' => 'Месячная Прибыль',
    'year_income' => 'Годовая Прибыль',
    'today_sales' => 'Сегодняшние продажи',
    'week_sales' => 'Недельные Распродажи',
    'month_sales' => 'Месячные Продажи',
    'year_sales' => 'Годовой Объем продаж',
    'top_selling_classes' => 'Самые продаваемые Курсы',
    'top_selling_appointments' => 'Самые продаваемые встречи',
    'top_selling_instructors' => 'Самые продаваемые Преподователи',
    'view_more' => 'Посмотреть Больше ',
    'classes_durations' => 'Продолжительность Курса',
    'top_selling_organizations' => 'Самые продаваемые Организации',
    'most_active_students' => 'Самые Активные Ученики',
    'reserved_appointments' => 'Зарезервированные Встречи',
    'total_purchased_amount' => 'Общая Сумма Покупки',
    'classes_statistics' => 'Типы курсов',

//Discounts

    'discount_list_page_title' => 'Список скидок',
    'discount' => 'Скидка',
    'discount_percentage' => 'Процент Скидки',
    'expiration_from' => 'С Даты Истечения Срока Годности',
    'expiration_to' => 'До Истечения Срока Годности',
    'all_users_discount' => 'Все Скидки',
    'remain' => 'Оставшийся',
    'usable_times' => 'Время использования',
  	'expire_date' => 'Дата истечения срока действия',

//Filters

    'filter' => 'Фильтр',
    'filters' => 'Фильтры',
    'add_options' => 'Добавление параметров Фильтра',
    'option' => 'Вариант',
    'filter_option' => 'Опция Фильтрации',
    'filters_list_page_title' => 'Список фильтров',
    'admin_filters' => 'Фильтры',
    'admin_filters_list' => 'Список фильтров',
    'admin_filters_create' => 'Создать фильтр',
    'admin_filters_edit' => 'Фильтры Редактировать',
    'admin_filters_delete' => 'Удаление фильтров',

//Filters Types

    'percentage_ascending' => 'Процент - По возрастанию',
    'percentage_descending' => 'Процент - По убыванию',
    'max_amount_ascending' => 'Максимальная сумма - По возрастанию',
    'max_amount_descending' => 'Максимальная сумма - По убыванию',
    'usable_times_ascending' => 'Время использования - По возрастанию',
    'usable_times_descending' => 'Время использования - По убыванию',
    'usable_times_remain_ascending' => 'Оставшееся Время Использования - По Возрастанию',
    'usable_times_remain_descending' => 'Оставшееся Время Использования - По Убыванию',
    'create_date_ascending' => 'Дата создания - По возрастанию',
    'create_date_descending' => 'Дата создания - По убыванию',
    'expire_date_ascending' => 'Срок годности - Возрастающий',
    'expire_date_descending' => 'Срок годности - По убыванию',
    'update_date_ascending' => 'Дата обновления - По возрастанию',
    'update_date_descending' => 'Дата обновления - По убыванию',
    'date_ascending' => 'Дата - По возрастанию',
    'date_descending' => 'Дата - По убыванию',
    'amount_ascending' => 'Сумма - По возрастанию',
    'amount_descending' => 'Сумма - По убыванию',
    'Transaction_time_ascending' => 'Время транзакции - По возрастанию',
    'Transaction_time_descending' => 'Время транзакции - По убыванию',
    'last_payout_date_ascending' => 'Дата последней выплаты - По возрастанию',
    'last_payout_date_descending' => 'Дата последней выплаты - По убыванию',
    'quizzes_have_certificate' => 'Викторины с сертификатом',
    'students_ascending' => 'Студенты - По возрастанию',
    'students_descending' => 'Студенты - По убыванию',
    'passed_students_ascending' => 'Пройденные Студенты - Восходящие',
    'passes_students_descending' => 'Прошли Студенты - По убыванию',
    'grades_average_ascending' => 'Средний Балл - По Возрастанию',
    'grades_average_descending' => 'Средний Балл - По убыванию',
    'classes_sales_ascending' => 'Продажи курса - По возрастанию',
    'classes_sales_descending' => 'Продажи курса - По убыванию',
    'purchased_classes_ascending' => 'Приобретенные Курсы - По возрастанию',
    'purchased_classes_descending' => 'Приобретенные Курсы - По убыванию',
    'purchased_classes_amount_ascending' => 'Сумма покупки - По возрастанию',
    'purchased_classes_amount_descending' => 'Сумма Покупки - По убыванию',
    'sales_appointments_ascending' => 'Продажи встреч - По возрастанию',
    'sales_appointments_descending' => 'Встреча продаж - По убыванию',
    'appointments_income_ascending' => 'Доход от собраний - По возрастанию',
    'appointments_income_descending' => 'Доходы от собраний - По убыванию',
    'pending_appointments_ascending' => 'Ожидающие встречи - По возрастанию',
    'pending_appointments_descending' => 'Незавершенные заседания - По убыванию',
    'purchased_appointments_ascending' => 'Приобретенные Встречи - По возрастанию',
    'purchased_appointments_descending' => 'Приобретенные Встречи - По убыванию',
    'purchased_appointments_amount_ascending' => 'Количество Приобретенных Встреч - По возрастанию',
    'purchased_appointments_amount_descending' => 'Количество Приобретенных Встреч - По убыванию',
    'register_date_ascending' => 'Дата регистрации - По возрастанию',
    'register_date_descending' => 'Дата регистрации - По убыванию',
    'discounted_classes' => 'Курсы со скидкой',
    'sales_ascending' => 'Продажи - По возрастанию',
    'sales_descending' => 'Продажи - По убыванию',
    'Price_ascending' => 'Цена - По возрастанию',
    'Price_descending' => 'Цена - Нисходящая',
    'Income_ascending' => 'Доход - Возрастающий',
    'Income_descending' => 'Доход - По убыванию',
    'cost_ascending' => 'Сумма - По возрастанию',
    'cost_descending' => 'Сумма - По убыванию',
    'discounted_appointments' => 'Встречи со скидкой',
    'free_appointments' => 'Бесплатные Встречи',

//Financial

    'financial' => 'Финансовый',
    'accounting' => 'Учет',
    'discounts' => 'Скидки',
    'discount_code' => 'Код скидки',
    'discount_codes' => 'Коды скидок',
    'code' => 'Код',
    'count' => 'Рассчитывать',
    'max_amount' => 'Максимальное Количество',
    'percentage' => 'Процент',
    'name_placeholder' => 'Напишите уникальный заголовок...',
    'count_placeholder' => 'Максимальное количество раз, когда можно использовать код скидки (оставьте его пустым для времени "1".)',
    'expiration' => 'Дата истечения срока действия',
    'ext_date' => 'Дата истечения срока действия',
    'percent' => 'Процент',
    'amount' => 'Сумма',
    'paid_amount' => 'Сумма',
    'amount_placeholder' => 'Максимальная сумма скидки на заказ.',
    'payout' => 'Выплата',
    'payouts' => 'Выплаты',
    'payout_amount' => 'Сумма Выплаты',
    'account' => 'Счет',
    'iban' => 'Код IBAN',
    'transaction_time' => 'Время транзакции',
    'last_payout_date' => 'Дата Последней Выплаты',
    'sale' => 'Распродажа',
    'sales' => 'Продажи',
    'sales_list' => 'Список продаж',
    'sale_type' => 'Тип продаж',
    'file' => 'Файл',
    'meeting' => 'Встреча',
    'ticket' => 'Билет',
    'seller' => 'Продавец',
    'buyer' => 'Покупатель',
    'waiting_payment' => 'Ожидание оплаты',
    'delivered' => 'Доставлен',
    'paid_failed' => 'Оплачено/Не удалось',
    'paid_waiting' => 'Оплачено/В ожидании',
    'paid_successful' => 'Оплаченный/Успешный',
    'success' => 'Успешный',
    'invoice' => 'Счет-фактура',
  	'purchase_date' => 'Дата Покупки',

    'offline_payment' => 'Автономный Платеж',
    'offline_payments' => 'Автономные Платежи',
    'off' => 'Прочь',
    'bank' => 'Банк',
    'all_banks' => 'Все Банки',
    'referral_code' => 'Ссылка',
    'documents' => 'Документы',
    'new_document' => 'Новый документ',
    'addiction' => 'Добавь',
    'deduction' => 'Вычитать',
    'creator' => 'Создатель',
    'automatic' => 'Автоматический',
    'target_account' => 'Целевой счет',
    'income' => 'Доход',
    'user_income' => 'Доход пользователя',
    'account_balance' => 'Баланс счета',
    'factor' => 'Фактор',
    'new_factor' => 'Новый Фактор',
    'sales_page_title' => 'Продажи',
    'webinar' => 'Вебинар',
    'type_account' => 'Тип учетной записи',
    'item_purchased' => 'Приобретенный Товар',
    'asset' => 'Бумажник',
    'document_page_title' => 'Финансовые документы',
    'financial_settings' => 'Финансовые условия',
    'system' => 'Система',
    'tax' => 'Налог',
    'new_document_page_title' => 'Новый документ',
    'bank_name' => 'Название банка',
    'account_name' => 'Название учетной записи',
    'account_number' => 'Номер счета',
    'account_id' => 'Счет ID',
    'verify_user' => 'Проверка пользователя',
    'financial_approval' => 'Финансовое одобрение',
    'user_commission' => 'Комиссия Пользователя',
    'commission' => 'Комиссия',
    'user_commission_placeholder' => 'Оставьте его пустым, чтобы использовать системную скорость по умолчанию.',
    'offline_payment_page_title' => 'Автономный Платеж',
    'refund' => 'Возврат',
    'manual_document' => 'Ручной документ',
    'automatic_document' => 'Автоматический документ',
    'new_subscribe' => 'Новый Пакет подписки',
    'purchased_subscribe' => 'Приобретенный Пакет Подписки',
    'purchased_promotion' => 'Приобретенный План Продвижения',
    'subscribe' => 'Подписываться',
    'new_package' => 'Новый Пакет',
    'subscribes' => 'Подписываться',
  	'packages' => 'Пакеты',
  	'subscribe_packages' => 'Пакеты подписки',
    'usable_count' => 'Время подписки',
    'short_description' => 'Описание',
    'short_description_placeholder' => 'Пример: Рекомендуется для профессионалов.',
    'promotion' => 'Продвижение',
    'promotions' => 'Планы продвижения по службе',
    'is_popular' => 'Популярный значок',
  	'new_plan' => 'Новый План',
  	'plans' => 'Планы',
    'new_promotion' => 'Новый План Продвижения по Службе',
    'edit_promotion' => 'Изменить План Продвижения',
    'payment_channels' => 'Платежные шлюзы',
    'special_offers' => 'Скидки на Курсы',
    'special_offers_list_page_title' => 'Скидки на Курсы',
    'from_date' => 'С Даты',
    'to_date' => 'Датировать',
    'document_number' => 'ID Документа',

//Groups

    'group_list_page_title' => 'Список групп',
    'group' => 'Группа',
    'admin_group' => 'Группы',
    'admin_group_list' => 'Список групп',
    'admin_group_create' => 'Группы Создают',
    'admin_group_edit' => 'Группы Править',
    'admin_group_delete' => 'Группы Удаляются',

//Payment Gateways

    'payment_channel' => 'Платежный шлюз',
    'payment_channel_edit' => 'Редактировать Платежный шлюз',
    'payment_channel_count' => 'Категории',
    'admin_payment_channel' => 'Платежный шлюз',
    'admin_payment_channel_list' => 'Список платежных шлюзов',
    'admin_payment_channel_create' => 'Платежные Шлюзы Создают',
    'admin_payment_channel_edit' => 'Платежные Шлюзыправить',
    'admin_payment_channel_delete' => 'Платежные шлюзы Удаляют',

//Quiz

    'quizzes' => 'Викторины',
    'quizzes_list' => 'Список викторин',
    'quiz_results' => 'Результаты',
    'question_count' => 'Вопросы',
    'students_count' => 'Студенты',
    'average_grade' => 'Средняя Оценка',
    'grade' => 'Класс',
    'quiz_date' => 'Дата проведения викторины',
    'passed' => 'Пройденный',
    'certificates' => 'Сертификаты',
    'certificates_templates' => 'Шаблоны сертификатов',
    'templates' => 'Шаблоны',
    'new_template' => 'Новый Шаблон',
    'template_image' => 'Фоновое изображение',
    'position_x' => 'Позиция X',
    'position_y' => 'Позиция Y',
    'font_size' => 'Размер шрифта',
    'text_color' => 'Цвет текста',
    'message_body' => 'Текст',
    'preview_certificate' => 'Предварительный просмотр',
    'admin_quizzes' => 'Викторины',
    'admin_quizzes_list' => 'Список викторин',
    'admin_quizzes_create' => 'Викторины Создают',
    'admin_quizzes_edit' => 'Викториныправить',
    'admin_quizzes_delete' => 'Тесты Удалить',

//Quiz Results

    'quiz_result_list_page_title' => 'Результаты викторины',
    'admin_quiz_result' => 'Результаты викторины',
    'admin_quiz_result_list' => 'Список результатов викторины',
    'admin_quiz_result_create' => 'Результаты викторины Создают',
    'admin_quiz_result_edit' => 'Результаты Викториныправить',
    'admin_quiz_result_delete' => 'Результаты викторины Удалить',

//User Roles

    'role' => 'Роль',
    'roles' => 'Роли пользователей',
    'all_roles' => 'Все Роли',
    'select_sections_level' => 'Выберите уровень разделов',
    'page_lists_title' => 'Список ролей пользователей',
    'role_new_page_title' => 'Новая роль',
    'permission' => 'Разрешения',
    'permission_description' => 'Проверьте меню, подменю и действия, которые вы хотите разрешить пользователю.',
    'sections' => 'Разделы',
    'select_type' => 'Выберите тип',
    'create_field_name_placeholder' => 'Например, Финансовый персонал',
    'is_admin' => 'Доступ к панели Администратора',
    'admin_roles' => 'Роли',
    'admin_roles_list' => 'Список ролей',
    'admin_roles_create' => 'Роли Создают',
    'admin_roles_edit' => 'Роли Править',
    'admin_roles_delete' => 'Роли Удаляются',

// Pages Title
  
    'webinar_new_page_title' => 'Новый Курс',
    'tag_new_page_title' => 'Новый Тег',
    'group_new_page_title' => 'Новая Группа пользователей',
    'filter_new_page_title' => 'Новый Фильтр',
    'category_new_page_title' => 'Новая категория',
    'user_new_page_title' => 'Новый Пользователь',

//Settings

    'setting' => 'Настройки',
    'settings' => 'Настройки',
    'basic' => 'Основной',
    'offline_banks_credits' => 'Автономные Платежные Счета',
    'overview' => 'Контролировать Все',
    'change_setting' => 'Изменение настроек',
    'overview_hint' => 'Вы можете изменить все параметры и переменные, используя следующие карточки.',
    'general_card_title' => 'Общие',
    'general_card_hint' => 'Измените название веб-сайта, логотип, язык, RTL, социальные аккаунты, стили дизайна, предварительную загрузку.',
    'financial_card_title' => 'Финансовый',
    'financial_card_hint' => 'Определение mpmissions, налогов, выплат, валюты, платежных шлюзов, автономных платежей',
    'personalization_card_title' => 'Персонализация',
    'personalization_card_hint' => 'Меняйте фон страницы, домашние разделы, стили героев, изображения и тексты.',
    'notifications_card_title' => 'Уведомления',
    'notifications_card_hint' => 'Назначьте шаблоны уведомлений процессам.',
    'seo_card_title' => 'Оптимизация Поисковых Систем',
    'seo_card_hint' => 'Определите заголовок Оптимизация Поисковых Систем, мета-описание и доступ к обходу поисковой системы для каждой страницы.',
    'customization_card_title' => 'Настройка',
    'customization_card_hint' => 'Определите дополнительные коды CSS и JS.',
    'personalization' => 'Персонализация',

// Settings - SEO

    'seo_metas' => 'Мета-настройки Оптимизация Поисковых Систем',
    'seo_metas_home' => 'Домашняя страница',
    'seo_metas_search' => 'Страница поиска',
    'seo_metas_categories' => 'Страница Категорий',
    'seo_metas_classes' => 'Страница Курсов',
    'seo_metas_login' => 'Страница Входа в Систему',
    'seo_metas_register' => 'Страница Регистрации',
    'seo_metas_about' => 'О странице',
    'seo_metas_contact' => 'Страница Контактов',
    'seo_metas_certificate_validation' => 'Проверка подлинности сертификата',
    'seo_description' => 'Оптимизация Поисковых Систем-Мета-описание',
    'seo_metas_blog' => 'Блог',
    'seo_metas_instructors' => 'Инструкторы',
    'seo_metas_organizations' => 'Организации',




































    'settings_socials' => 'Настройки социальных аккаунтов',
    'socials' => 'Социальные аккаунты',

// Settings-footer

    'footer' => 'Нижний колонтитул',
    'footer_first_column' => 'Первая колонка',
    'footer_second_column' => 'Вторая колонка',
    'footer_third_column' => 'Третья колонка',
    'footer_forth_column' => 'Четвертая колонка',
    'content' => 'Содержание',
    'item_title' => 'Название элемента',
    'item_link' => 'URL-адрес элемента',

// Settings-main

    'main' => 'Главный',
    'home_sections' => 'Главная Разделы',
    'settings_home_sections' => 'Главная Разделы',
    'settings_main' => 'Основные параметры',
    'main_general' => 'Общий',
    'site_name' => 'Название платформы',
    'site_email' => 'Электронная почта платформы',
    'site_phone' => 'Телефон платформы',
    'site_language' => 'Язык интерфейса по умолчанию',
    'default_language_hint' => 'Чтобы изменить язык для администратора или персонала, перейдите в меню «Пользователи», отредактируйте пользователя и выберите язык для пользователя.',
    'register_method' => 'Способ регистрации',
    'user_languages_lists' => 'Список языков внешнего интерфейса',
    'rtl_languages' => 'Языки с письмом справа налево',
    'fav_icon' => 'Фавикон',
    'fav_icon_placeholder' => 'Отображается поверх браузера (16*16px)',
    'logo' => 'Логотип',
    'logo_placeholder' => 'Отображается в заголовке (~140*44px)',
    'footer_logo' => 'Логотип нижнего колонтитула',
    'webinar_reminder_schedule' => 'Расписание напоминаний о вебинарах (час)',
    'footer_logo_placeholder' => 'Отображает нижний колонтитул на всех страницах (~140*44px)',
    'rtl_layout' => 'Включить RTL-макет',
    'preloading' => 'Включить предварительный загрузчик',
    'main_financial' => 'финансовый',
    'minimum_payout_amount' => 'Минимальная сумма выплаты',
    'main_payment' => 'Оплата',
    'currency' => 'Валюта',
    'gateways' => 'Шлюзы',

    'main_home_hero' => 'Полноразмерный стиль героя',
    'main_home_hero2' => 'Анимированный стиль героя',
    'home_hero' => 'Полноразмерный стиль героя',
    'home_hero2' => 'Анимированный стиль героя',
    'background' => 'Фон',
    'hero_background' => 'Предыстория героя',
    'hero_vector' => 'Фон героя (или анимация .JSON)',
    'has_lottie' => 'Включить анимацию Лотти',

    'main_page_background' => 'Фон страниц',
    'admin_login_background' => 'Страница входа администратора',
    'admin_dashboard_background' => 'Панель администратора',
    'login_background' => 'Авторизоваться',
    'register_background' => 'Регистрация',
    'remember_pass_background' => 'Восстановление пароля',
    'verification_background' => 'Страница подтверждения',
    'search_background' => 'Страница поиска',
    'categories_background' => 'Категории',
    'become_instructor_background' => 'Страница «Стать инструктором»',
    'certificate_validation_background' => 'Страница проверки сертификата',
    'blog_background' => 'Блог',
    'instructors_background' => 'Страница со списком инструкторов',
    'organizations_background' => 'Страница со списком организаций',
    'dashboard_background' => 'Верхнее изображение пользовательской панели',
    'user_avatar_background' => 'Изображение профиля пользователя по умолчанию',
    'user_cover_background' => 'Обложка профиля пользователя по умолчанию',
    'custom_css_js' => 'Пользовательские CSS и JS',
    'css' => 'CSS',
    'js' => 'JS',
    'account_types' => 'Типы учетных записей',
    'add_account_types' => 'Добавить типы учетных записей',
    'site_bank_accounts' => 'Банковские счета сайта',
    'add_site_bank_accounts' => 'Добавить банковские счета',
    'report_reasons' => 'Сообщить о причинах',
    'add_report_reasons' => 'Добавить причину отчета',
    'notifications' => 'Уведомления',
    'notification_admin' => 'Администратор',
    'notification_user' => 'Пользователи',
    'notification_course' => 'Курсы',
    'notification_financial' => 'финансовый',
    'notification_sale_purchase' => 'Продажи/покупки',
    'notification_plans' => 'Подписка',
    'notification_appointment' => 'Встречи',
    'notification_quiz' => 'викторины',
    'panel_sidebar' => 'Боковая панели пользователя',

    'notification_new_comment_admin' => 'Новый комментарий',
    'notification_support_message_admin' => 'Новое сообщение службы поддержки',
    'notification_support_message_replied_admin' => 'Ответить на сообщение поддержки',
    'notification_promotion_plan_admin' => 'План продвижения зарезервирован',
    'notification_new_contact_message' => 'Новое контактное сообщение',
    'notification_new_badge' => 'Новый значок',
    'notification_change_user_group' => 'Изменение группы пользователей',
    'notification_course_created' => 'Представление курса',
    'notification_course_approve' => 'Утверждение курса',
    'notification_course_reject' => 'Отклонение курса',
    'notification_new_comment' => 'Новый комментарий',
    'notification_support_message' => 'Новое сообщение службы поддержки',
    'notification_support_message_replied' => 'Ответ на сообщение службы поддержки',
    'notification_new_rating' => 'Новый рейтинг',
    'notification_webinar_reminder' => 'Напоминание о вебинаре',
    'notification_new_financial_document' => 'Новый финансовый документ',
    'notification_payout_request_admin' => 'Новый запрос на выплату',
    'notification_payout_request' => 'Подача запроса на выплату',
    'notification_payout_proceed' => 'Выплата обработана',
    'notification_offline_payment_request' => 'Новый офлайн-запрос платежа',
    'notification_offline_payment_approved' => 'Офлайн-оплата одобрена',
    'notification_offline_payment_rejected' => 'Офлайн-платеж отклонен',
    'notification_new_sales' => 'Новые продажи',
    'notification_new_purchase' => 'Новая покупка',
    'notification_new_subscribe_plan' => 'Новый план подписки',
    'notification_promotion_plan' => 'План продвижения активирован',
    'notification_new_appointment' => 'Новая встреча',
    'notification_new_appointment_link' => 'URL-адрес встречи создан',
    'notification_appointment_reminder' => 'Напоминание о встрече',
    'notification_meeting_finished' => 'Встреча завершена',
    'notification_new_certificate' => 'Новый сертификат',
    'notification_waiting_quiz' => 'Новая викторина ожидания',
    'notification_waiting_quiz_result' => 'Ожидание результатов',

    'contact_us' => 'Контакт',
    'contact_us_edit' => 'Контактная страница Редактировать',
    'contact_us_address' => 'Адрес',
    'contact_us_phones' => 'Телефоны',
    'contact_us_emails' => 'электронные письма',
    'contact_us_background' => 'Фон страницы контактов',
    'map_position' => 'Положение на карте (широта и долгота)',
    'map_zoom' => 'Уровень масштабирования карты (предпочтительно от 15 до 19)',
    'map_position_latitude' => 'Широта карты',
    'map_position_longitude' => 'Долгота  карты',
    'contact_us_phones_placeholder' => 'Разделяйте запятыми ","',
    'contact_us_emails_placeholder' => 'Разделяйте запятыми ","',

    '404_page_setting' => '404 Настройка страницы',
    'error_404' => '404 Страница',
    'error_404_image' => '404 Изображение',
    'error_404_title' => '404 Название ошибки',
    'error_404_description' => '404 Описание ошибки',

    'pages' => 'Страницы',
    'new_page' => 'Новая страница',
    'new_pages' => 'Новая дополнительная страница',
    'edit_pages' => 'Отредактируйте страницу ',
    'pages_title_placeholder' => 'Отображается в шапке страницы',
    'robot' => 'SEO-доступ к роботам',
    'follow' => 'Следовать',
    'no_follow' => 'Не следует',

    'latest_classes' => 'Последние курсы',
    'best_sellers' => 'Бестселлеры',
    'free_classes' => 'Бесплатные курсы',
    'discount_classes' => 'Курсы со скидкой',
    'best_rates' => 'Курсы с лучшим рейтингом',
    'trend_categories' => 'Популярные категории',
    'organizations_section' => 'Раздел организаций',
    'instructors' => 'Инструкторы',
    'video_or_image_section' => 'Раздел видео/изображений',
    'settings_navbar_links' => 'Лучшие ссылки на панели навигации',
    'navbar_links' => 'Лучшие ссылки на панели навигации',
    'top_navbar' => 'Верхняя панель навигации',
    'pages_backgrounds' => 'Фоны страниц',
    'hero_style_1' => 'Полноразмерный стиль героя',
    'Hero_style_2' => 'Анимированный стиль героя',
    'video_and_image_sections' => 'Раздел видео/изображений',
    'change_password' => 'Сменить пароль',
	'select_a_partner_hint' => 'Инструктор-партнер будет иметь доступ к содержанию курса, и его профиль будет отображаться на странице курса.',

//Tags

    'tag' => 'Тег',
    'tags' => 'Теги',
    'tags_list_page_title' => 'Список тегов',
    'admin_tags' => 'Теги',
    'admin_tags_list' => 'Список тегов',
    'admin_tags_create' => 'Теги Создать',
    'admin_tags_edit' => 'Отредактировать тэги',
    'admin_tags_delete' => 'Удалить теги',
  	'create_field_title_placeholder' => 'Теги будут отображаться на странице курса.',

//Users

    'users_list' => 'Пользователи',
    'user_or_instructor' => 'Пользователь или инструктор',
    'users' => 'Пользователи',
    'classes' => 'Курсы',
    'class' => 'Курс',
    'classes_sales' => 'Продажа курсов',
    'purchased_classes' => 'Приобретенные курсы',
    'appointments' => 'Встречи',
    'appointment' => 'Встреча',
    'appointments_sales' => 'Продажи встреч',
    'purchased_appointments' => 'Приобретенные встречи',
    'wallet_charge' => 'Баланс',
    'user_group' => 'Группа пользователей',
    'user_group_commission_rate' => 'Комиссионная ставка (для инструкторов и организаций)',
    'user_group_discount_rate' => 'Ставка скидки (для всех пользователей)',
    'instructor' => 'Инструктор',
    'students' => 'Ученики',
    'student' => 'Ученик',
    'staff' => 'Персонал',
    'organization' => 'Организация',
    'organizations' => 'Организации',
    'organizations_list' => 'Список организаций',
    'select_organization' => 'Выберите организацию',
    'all_user_roles' => 'Все роли пользователей',
    'active_verified' => 'Активный (с синим значком)',
    'verified' => 'с синим значком',
    'not_verified' => 'без синего значка',
    'enable_blue_badge' => 'Включить синий значок',
    'active_not_verified' => 'Активный (без синего значка)',
    'role_name' => 'Роль пользователя',
    'admin_role' => 'Администратор',
    'full_name' => 'Имя',
    'users_count' => 'Количество пользователей',
    'create_field_full_name_placeholder' => 'Имя пользователя будет отображаться на всех страницах.',
    'select_role' => 'Выберите роль пользователя',
    'select_status' => 'Выберите статус',
    'create_field_email_placeholder' => 'Пример: имя пользователя@gmail.com',
    'search_user_or_instructor' => 'Поиск пользователя или инструктора',
    'select_a_instructor' => 'Выберите инструктора',
  	'search_instructor' => 'Поиск инструктора',
  	'search_student' => 'Поиск студента',
  	'search_users' => 'Поиск пользователей',

///User Badges

    'select_badge' => 'Выберите значок',
    'badges' => 'Значки',
    'register_date' => 'Дата регистрации',
    'course_count' => 'Количество курсов',
    'course_rate' => 'Рейтинг курсов',
    'sale_count' => 'Количество продаж',
    'support_rate' => 'Рейтинг поддержки',
    'condition' => 'Состояние',
    'condition_register_date' => 'День',
    'condition_course_count' => 'Курсы',
    'condition_course_rate' => 'Звезды',
    'condition_sale_count' => 'Продажи',
    'condition_support_rate' => 'Звезды',
    'groups' => 'Группы',
    'group_name' => 'Название группы',
    'users_groups' => 'Группы пользователей',
    'users_group' => 'Группа пользователей',
    'select_users_group' => 'Выберите группу пользователей',
    'new_user_group' => 'Новая группа пользователей',
    'admin_users' => 'Пользователи',
    'admin_users_list' => 'Список пользователей',
    'admin_users_create' => 'Создать пользователя',
    'admin_users_edit' => 'Изменить пользователей',
    'admin_users_delete' => 'Удалить пользователей',
    'admin_users_badges' => 'Значки пользователей',
    'edit_page_title' => 'Изменить пользователя',
    'custom_badges' => 'Пользовательские значки',
    'auto_badges' => 'Автоматические значки',
    'supports' => 'Поддерживать',
    'department' => 'Отделение',
    'support_departments' => 'Отделы поддержки',
    'new_department' => 'Новый отдел',
    'edit_department' => 'Редактировать отдел',
    'departments' => 'Департаменты',
    'all_departments' => 'Все отделы',
    'classes_conversations' => 'Поддержка курсов',
    'course_conversations' => 'Беседы курса',
    'support_conversation' => 'Поддержка разговора',
    'close_conversation' => 'Закрытый разговор',
    'open_attach' => 'Открыть вложение',
    'send_message_to' => 'Отправить сообщение',
    'send_message_to_teacher' => 'Отправить сообщение инструктору',
    'user_avatar' => 'Изображение профиля',
    'user_bio' => 'Название работы',
    'rate' => 'Рейтинг',

//Notification Template

    'notification_single' => 'Один пользователь',
    'notification_all_users' => 'Все пользователи',
    'notification_students' => 'Все студенты',
    'notification_instructors' => 'Все инструкторы',
    'notification_organizations' => 'Все организации',
    'notification_all' => 'Все',
    'notification_students_and_instructors' => 'Студенты и преподаватели',
    'notification_group' => 'Конкретная группа пользователей',
    'mark_all_read' => 'Отметить все как прочитанное',
    'use_key_in_title_and_message_body' => 'Вы можете использовать указанные выше теги данных в заголовке и основном тексте шаблона.',
    'edit_template' => 'Изменить шаблон',
    'real_name' => 'Полное имя пользователя',
    'group_title' => 'Название группы пользователей',
    'badge_title' => 'Название значка',
    'financial_doc_desc' => 'Описание финансового документа',
    'financial_doc_type' => 'Тип финансового документа',
    'instructor_name' => 'Имя инструктора',
    'student_name' => 'Имя студента',
    'course_title' => 'Название курса',
    'quiz_title' => 'Название викторины',
    'quiz_result' => 'Результат (Оценка)',
    'support_ticket_title' => 'Название обращения в службу поддержки',
    'contact_us_title' => 'Заголовок контактного сообщения',
    'time_and_date' => 'Время и дата',
    'rate_count' => 'Рейтинг (звезды)',
    'payout_account' => 'Счет выплат',
    'subscribe_plan_name' => 'Название пакета подписки',
    'promotion_plan_name' => 'Название плана продвижения',

//Instructor Requests

    'reject_request' => 'Отклонять',
    'become_instructor_info' => 'Сведения о запросе инструктора',
    'become_instructors' => 'Запросы инструктора',
    'instructor_requests' => 'Запросы инструктора',
    'accept_request' => 'Принимать',
    'check_user_information' => 'Проверить информацию о пользователе',
    'become_instructors_list' => 'Сведения о запросе инструктора',
    'contacts' => 'Контактные сообщения',
    'contacts_lists' => 'Списки контактных сообщений',
    'contacts_message' => 'Контактное сообщение',
    'user_role_updated' => 'Роль пользователя обновлена.',

//Classes

    'webinars_list_page_title' => 'Список живых занятий',
    'webinars' => 'Живые классы',
    'live_class' => 'Живой класс',
    'live_classes' => 'Живые классы',
    'text_courses' => 'Текстовые курсы',
    'webinar_title' => 'Название курса',
    'webinar_status' => 'Статус курса',
    'start_date' => 'Дата начала',
    'end_date' => 'Дата окончания',
    'capacity' => 'Вместимость',
    'price' => 'Цена',
    'price_plans' => 'Тарифные планы',
    'add_price_plan' => 'Новый тарифный план',
    'description' => 'Описание',
    'course_type' => 'Тип курса',
    'type_webinar' => 'Вебинар',
    'type_text_lesson' => 'Текстовый курс',
    'type_course' => 'Курс',
    'type_webinars' => 'Живой класс',
    'type_text_lessons' => 'Текстовый курс',
    'type_courses' => 'Курсы',
    'teacher_name' => 'Инструктор',
    'category_name' => 'Категория',
    'select_category' => 'Выбрать категорию',
    'select_teacher' => 'Выберите инструктора',
    'webinars_count' => 'Курсы',
    'image_cover' => 'Изображение обложки',
    'choose_image_cover' => 'Выберите обложку',
    'choose_video_demo' => 'Выберите демонстрационное видео',
    'video_demo' => 'Демонстрационное видео',
    'support' => 'Поддерживать',
    'partner_instructor' => 'Инструктор-партнер',
    'search_webinar' => 'Поиск курса',
    'admin_webinars' => 'Вебинары',
    'admin_webinars_list' => 'Список курсов',
    'admin_webinars_create' => 'Новый курс',
    'admin_webinars_edit' => 'Редактировать курс',
    'admin_webinars_delete' => 'Удалить курс',
    'feature_webinars' => 'Избранные курсы',
    'feature_webinar_create' => 'Новый рекомендуемый курс',
    'page' => 'Страница',
    'select_page' => 'Выберите страницу',
    'page_home' => 'Домашняя страница',
    'page_categories' => 'Категории',
    'page_home_categories' => 'Главная & Категории',
    'file_sale_count' => 'Продажа файлов',
    'session_sale_count' => 'Сессионные продажи',
    'lesson_sale_count' => 'Продажи уроков',
    'not_conducted' => 'Не проводится',
    'conducted' => 'Проведенный',
    'publish_not_conducted' => 'Опубликовано (не проведено)',
    'publish_inprogress' => 'Опубликовано (в процессе)',
    'publish_finished' => 'Опубликовано (завершено)',
    'teacher_zoom_jwt_token_invalid' => 'Неверные учетные данные инструктора Zoom!',
    'session_api' => 'API сеанса',
    'is_not_the_teacher_of_this_organization' => 'Выбранный инструктор не существует или не имеет отношения к этой организации.',
    'webinars_reports' => 'Отчеты о курсах',

  // Noticeboard Page
  
    'edit_noticeboard' => 'Изменить уведомление',
    'send_noticeboard_success' => 'Уведомление успешно отправлено.',
    'edit_noticeboard_success' => 'Уведомление успешно изменено.',
    'delete_noticeboard_success' => 'Уведомление успешно удалено.',

//Statistic

    'total_appointments' => 'Всего встреч',
    'open_appointments' => 'Открытые встречи',
    'finished_appointments' => 'Завершенные встречи',
    'total_consultants' => 'Всего консультантов',
    'total_comments' => 'Всего комментариев',
    'published_comments' => 'Опубликованные комментарии',
    'pending_comments' => 'Ожидающие комментарии',
    'available_consultants' => 'Доступные консультанты',
    'unavailable_consultants' => 'Недоступные консультанты',
    'consultants_without_appointment' => 'Консультанты без встреч',
    'total_sales' => 'Тотальная распродажа',
    'faild_sales' => 'Неудачные продажи',
    'total_quizzes' => 'Всего викторин',
    'total_students' => 'Всего студентов',
    'total_passed_students' => 'Всего успешно сдавших экзамены',
    'active_quizzes' => 'Активные викторины',
    'total_reviews' => 'Всего отзывов',
    'published_reviews' => 'Опубликованные обзоры',
    'rates_average' => 'Средний рейтинг',
    'classes_without_review' => 'Курсы без обзора',
    'total_conversations' => 'Всего разговоров',
    'open_conversations' => 'Открытые беседы',
    'closed_conversations' => 'Закрытые беседы',
    'closed' => 'Закрыто',
    'classes_with_support' => 'Курсы с поддержкой',
    'total_instructors' => 'Всего инструкторов',
    'organizations_instructors' => 'Инструкторы организаций',
    'inactive_instructors' => 'Неактивные инструкторы',
    'ban_instructors' => 'Неактивные инструкторы',
  	'banned' => 'Запрещено',
  	'until' => 'До того как',
    'total_organizations' => 'Всего организаций',
    'verified_organizations' => 'Проверенные организации',
    'organizations_students' => 'Организация Студенты',
    'inprogress_live_classes' => 'Текущие живые занятия',
    'total_durations' => 'Общая продолжительность',
    'inactive_students' => 'Неактивные студенты',
    'ban_students' => 'Запрещенные студенты',
    'users_without_purchases' => 'Пользователи без покупки',
    'teachers_without_class' => 'Инструкторы без курса',
    'featured_classes' => 'Избранные курсы',
    'active_discounts' => 'Активные скидки',
    'net_profit_statistics' => 'Статистика чистой прибыли (без налогов)',

//Hints & Placeholders

    'hints' => 'Подсказки',
  	'new_page_link_hint' => 'Начните с «/» и просто используйте маленькие заглавные буквы. Пример: /about, чтобы URL-адрес страницы был yourwebsiteurl.com/pages/about.',
    'consultants_hint_title_1' => 'Become a Consultant',
    'consultants_hint_title_2' => 'Pending Meetings',
    'consultants_hint_title_3' => 'Unavailable Consultants',
    'consultants_hint_description_1' => 'В этом списке будут отображаться инструкторы, которые определяют свое расписание собраний. Преподаватели могут определять расписание собраний на своей панели..',
    'consultants_hint_description_2' => 'Встречи, зарезервированные студентом, но еще не проведенные. Ожидание может быть в процессе или не запущено.',
    'consultants_hint_description_3' => 'Инструктор может быть временно недоступен. Они могут изменить статус в настройках собрания на панели пользователя..',
    'instructors_hint_title_1' => 'Добавить нового инструктора',
    'instructors_hint_title_2' => 'Активные инструкторы',
    'instructors_hint_title_3' => 'Синий значок',
    'instructors_hint_description_1' => 'Чтобы добавить инструктора, создайте нового пользователя с ролью «Организация» или вы можете изменить роль пользователя на странице редактирования пользователей или одобрить запросы стать инструктором на соответствующей странице.',
    'instructors_hint_description_2' => 'Инструкторы, которые подтвердили свой адрес электронной почты или номер телефона после процесса регистрации.',
    'instructors_hint_description_3' => 'Включите эту опцию вручную для выбранных инструкторов. В их профиле будет отображаться синий значок.',
    'organizations_hint_title_1' => 'Добавить Новую Организацию',
    'organizations_hint_title_2' => 'Статусы организаций',
    'organizations_hint_title_3' => 'Функциональность организаций',
    'organizations_hint_description_1' => 'Чтобы добавить новую организацию, создайте нового пользователя с ролью "Организация" или отредактируйте пользователя из списка пользователей, измените роль пользователя на "Организация" и сохраните. Пользователь будет обращен к организации.',
    'organizations_hint_description_2' => 'Организации, чей адрес электронной почты или номер телефона были подтверждены после процесса регистрации, будут считаться "Активными". Вы также можете определить синий значок для организаций.',
    'organizations_hint_description_3' => 'Каждая организация может включать в себя соответствующих преподавателей и студентов. Организации могут создавать общедоступные или частные классы.',
    'students_hint_title_1' => 'Новый студент',
    'students_hint_title_2' => 'Ожидающий/Активный',
    'students_hint_title_3' => 'Неактивен/Запрещен',
    'students_hint_description_1' => 'Вы можете добавить нового ученика из раздела "Пользователи/Новые" или заполнить регистрационную форму во интерфейсе платформы.',
    'students_hint_description_2' => 'Пользователи, подтвердившие свой адрес электронной почты или номер телефона, будут считаться "Активными", а пользователи, не прошедшие проверку по электронной почте или телефону, будут рассматриваться как "Ожидающие".',
    'students_hint_description_3' => 'Заблокированные пользователи не смогут войти в систему в течение определенного периода. Неактивные пользователи вообще не смогут войти в систему.',
    'appointments_hint_title_1' => 'Завершенные/Незавершенные Заседания',
    'appointments_hint_title_2' => 'Отмененные Встречи',
    'appointments_hint_title_3' => 'Открытые Заседания',
    'appointments_hint_description_1' => 'Встречи, время которых истекло, и консультант изменил статус на завершенные, будут рассматриваться как "Завершенные", а встречи, которые зарезервированы, но не начаты, будут рассматриваться как "Ожидающие".',
    'appointments_hint_description_2' => 'Администратор или сотрудники могут отменить встречу. Встречи не могли быть отменены консультантом или резерватором.',
    'appointments_hint_description_3' => 'Собрания, которые их "URL-адрес для присоединения" определен консультантом и находятся в процессе.',
    'user_group_discount_rate_placeholder' => 'Оставьте его пустым для 0%',
    'user_group_commission_rate_placeholder' => 'Оставьте его пустым для значения по умолчанию (определенного в настройках)',
    'seo_description_hint' => 'Будет отображаться на странице результатов поисковой системы. Предпочтительно 155~160 символов.',
    'price_plan_modal_capacity_hint' => 'Заполните его, если вы хотите ограничить количество проданных билетов. Пример: Только 5 студентов получат скидку 50%. ',
    'trend_hint_title_1' => 'Функциональность Трендов',
    'trend_hint_description_1' => 'Категории трендов будут отображаться на главной странице. Вы можете указать 6 категорий, чтобы получить больше просмотров с домашней страницы.',
    'new_role_admin_access_hint' => 'Включите его для создания администраторов или персонала.',
    'user_group_commission_rate_hint' => 'Это значение будет рассматриваться как ставка комиссии инструктора, а ставка по умолчанию будет проигнорирована.',
    'user_group_discount_rate_hint' => 'Пользователи получат этот тариф в качестве дополнительной скидки на все покупки.',
    'badges_hint_title_1' => 'Автоматические Значки',
    'badges_hint_title_2' => 'Ручные значки',
    'badges_hint_description_1' => 'Значки будут выдаваться пользователям, если у них есть условия для получения значков. Значки будут отображаться в профиле пользователя.',
    'badges_hint_description_2' => 'Вы также можете присвоить каждому пользователю ручные и пользовательские значки. Ручные значки могут быть удалены вручную администратором или персоналом.',
    'become_instructor_hint_title_1' => 'Запросы инструктора',
    'become_instructor_hint_title_2' => 'Запрашивает Функциональность',
    'become_instructor_hint_description_1' => 'Если пользователь заполнит форму инструктора, запрос будет отображен в этом списке.',
    'become_instructor_hint_description_2' => 'Вы можете одобрить запросы инструктора, чтобы роль пользователя была преобразована в "Инструктор", или вы можете отклонить запросы, чтобы ничего не изменилось.',
    'report_reasons_hint' => 'Причины отчета будут отображаться в модальном режиме отчета, чтобы пользователь мог выбрать одну из них и сообщить.',
    'new_noticeboards_hint' => 'Уведомление будет отображаться на доске объявлений этих типов пользователей.',
    'new_notification_hint' => 'Уведомление будет получено этими пользователями и будет отображаться на их панели и адресе электронной почты.',
    'new_notification_template_hint_title_1' => 'Функциональность тегов данных',
    'new_notification_template_hint_title_2' => 'Назначение шаблонов процессам',
    'new_notification_template_hint_description_1' => 'Теги данных могут быть включены в заголовок или текст уведомления. Вы можете создавать персонализированные уведомления с помощью тегов данных.',
    'new_notification_template_hint_description_2' => 'После создания шаблона уведомления перейдите в раздел "Настройки/Уведомления" и назначьте шаблоны связанным процессам.',
    'create_blog_description_hint' => 'Краткое описание вашего сообщения в блоге, которое будет отображаться на карточке сообщения в блоге (~160 символов).',
    'create_blog_content_hint' => 'Основное содержимое записи в блоге, которое будет отображаться на странице записи в блоге.',
    'offline_payment_hint_title_1' => 'Функциональности файловых Платежей',
    'offline_payment_hint_title_2' => 'Автономные Платежные Счета',
    'offline_payment_hint_description_1' => 'Если пользователь отправит запрос на автономный платеж, он будет отображен в этом списке. Если запрос одобрен, сумма будет добавлена к балансу пользователя.',
    'offline_payment_hint_description_2' => 'Вы можете определить автономные платежные банки в разделе "Настройки / Финансы", чтобы они были доступны пользователям в форме автономного платежа.',
    'payout_list_hint_title_1' => 'Запросы на выплату',
    'payout_list_hint_title_2' => 'Функциональность выплат',
    'payout_list_hint_description_1' => 'Если инструктор или Организация запросили выплату, она будет отображена в этом списке. Они смогут запросить выплату, если их баланс будет больше минимальной суммы выплаты.',
    'payout_list_hint_description_2' => 'После того, как запрос на выплату будет одобрен администратором, баланс пользователя будет сброшен, и администратор должен перевести деньги на учетную запись пользователя вручную.',
    'subscribes_list_hint_title_1' => 'Пакеты подписки',
    'subscribes_list_hint_title_2' => 'Параметры пакетов',
    'subscribes_list_hint_description_1' => 'Пакеты подписки будут отображаться на главной странице и панели пользователя, и пользователи смогут приобретать их и подписываться на курсы, для которых включена опция подписки. Когда срок действия плана подписки истечет, у пользователя не будет доступа к контенту.',
    'subscribes_list_hint_description_2' => 'Время подписки: Количество курсов, на которые пользователь может подписаться. Дни: Продолжительность плана подписки. Популярный значок: значок будет отображаться на карточке пакета.',
    'discount_code_hint' => 'Пользователи будут использовать этот код для получения скидки (например, Merry_christmas)',
    'new_featured_hint_title_1' => 'Функциональность рекомендуемых курсов',
    'new_featured_hint_title_2' => 'Рекомендуемые курсы и должности',
    'new_featured_hint_description_1' => 'Избранные курсы будут отображаться иначе, чем обычные курсы, чтобы получить больше просмотров и трафика. Все рекомендуемые курсы включают значок "Рекомендуемые".',
    'new_featured_hint_description_2' => 'Они могут отображаться в верхней части домашней страницы (ползунок Избранных курсов) или в верхней части страницы категории.',
    'is_popular_hint' => 'Включите его, чтобы отобразить "Популярный" бюджет на карте.',
    'promotions_list_hint_title_1' => 'Функциональность Планов продвижения',
    'promotions_list_hint_title_2' => 'Как приобрести',
    'promotions_list_hint_title_3' => 'Процесс Продвижения Контента',
    'promotions_list_hint_description_1' => 'Преподаватели смогут приобрести рекламные планы для своих курсов, чтобы увеличить их просмотр, отображая курсы в лучших местах просмотра.',
    'promotions_list_hint_description_2' => 'Инструкторы могут приобрести планы продвижения по службе на своей панели. Инструктор должен указать курс в процессе покупки плана.',
    'promotions_list_hint_description_3' => 'Когда пользователь приобрел тарифный план, администратор может добавить выбранный курс в список лучших для просмотра, используя функции "Избранный курс" или "Рекламные баннеры".',
    'user_languages_lists_hint' => 'Эти языки будут отображаться для пользователей, и они смогут выбрать один из них.',
    'rtl_languages_hint' => 'Выберите языки, которые хотите загрузить в стиле RTL.',
    'minimum_payout_amount_hint' => 'Инструкторы / организации смогут отправить запрос на выплату, когда их баланс превысит это значение.',
    'default_commission_hint' => 'Ставка комиссии по умолчанию, которая будет рассчитана для платформы.',
    'seo_metas_hint_title_1' => 'SEO-Мета-описание',
    'seo_metas_hint_title_2' => 'Индекс/Без индекса',
    'seo_metas_hint_description_1' => 'Мета-описание не будет отображаться на странице, но оно будет отображаться на страницах результатов поисковой системы. Это должен быть мотивационный текст из 155 ~ 160 символов, чтобы побудить пользователей перейти по ссылке.',
    'seo_metas_hint_description_2' => 'Роботы и сканеры поисковых систем не смогут просматривать страницы без индекса, поэтому поисковые системы будут игнорировать эти страницы.',
    'has_lottie_hint' => 'Включите его, если выбран небольшой анимационный файл (.json)',
    'index' => 'Индекс',
    'no_index' => 'Нет Индекса',
  	'additional_pages_title' => 'Дополнительные Страницы',
  	'meetings_list_title' => 'Список встреч',
  	'consultants_list_title' => 'Список консультантов',
  	'marketing_dashboard_title' => 'Маркетинговая панель мониторинга',
  	'general_dashboard_title' => 'Приборная панель',
  	'discount_codes_title' => 'Коды скидок',
  	'new_discount_title' => 'Новая Скидка',
  	'edit_discount_title' => 'Редактировать Скидку',
  	'notices_list_title' => 'Список уведомлений',
  	'new_notice_title' => 'Новое Уведомление',
  	'offline_payments_title' => 'Автономные Платежи ',
  	'payouts_title' => 'Выплаты ',
   	'reviews_list_title' => 'Список отзывов',
   	'settings_title' => 'Настройки',
   	'new_product_discount_title' => 'Скидка на Новый Курс',
   	'edit_product_discount_title' => 'Изменить Скидку на Курс',
   	'support_departments_title' => 'Вспомогательные отделы',
   	'new_support_ticket_title' => 'Новый запрос в Службу поддержки',
   	'edit_support_ticket_title' => 'Редактировать запрос в службу поддержки',
   	'staff_list_title' => 'Штатное расписание',

//21 Aug Update
    'invited_instructor_hint' => 'Приглашенный преподаватель будет иметь доступ к содержимому курса. Их профиль будет показан на странице курса.',
  	'affiliate' => 'Филиал',
  	'referral' => 'Направления',
    'affiliate_users' => 'Партнерские пользователи',
    'referral_code' => 'Реферальный код',
    'referral_history' => 'История обращений',
  	'referrals_history' => 'Referral History',
    'referred_users' => 'Привлеченные Пользователи',
    'affiliate_amount' => 'Партнерская сумма',
    'registration_amount' => 'Регистрационная сумма',
    'total_commission_amount' => 'Общая Сумма Комиссии',
  	'affiliate_user_commission' => 'Комиссия партнерского пользователя',
    'affiliate_user' => 'Партнерский Пользователь',
    'active_users_affiliate_when_registration' => 'Активировать партнерскую программу для новых пользователей по умолчанию',
    'affiliate_users' => 'Партнерские пользователи',
    'affiliate_user_amount' => 'Бонус за регистрацию Партнерского Пользователя',
    'referred_user' => 'Привлеченный Пользователь',
    'referred_user_amount' => 'Бонус за регистрацию Привлеченного Пользователя',
    'referral_description' => 'Описание партнера',
    'affiliate_registration_amount' => 'Партнерский Бонус За Регистрацию',
    'total_affiliate_commission' => 'Общая Партнерская Комиссия',
  	'affiliate_user_commission' => 'Партнерская комиссия',
    'total_referred_amount' => 'общая перечисленная сумма',
  	'referred_user_amount' => 'Бонус Привлеченного Пользователя',
    'registration_income' => 'Регистрационный доход',
  	'aff_sales_commission' => 'Комиссия за продажу',
	'registeration_amount' => 'Регистрационная сумма',

    'affiliate_user_commission_hint' => 'Размер комиссии, которая будет начислена партнерскому пользователю при совершении покупки привлеченным пользователем (в процентах).',
    'affiliate_user_amount_hint' => 'Фиксированная сумма будет начислена партнерскому пользователю, когда пользователь зарегистрируется, используя партнерский код.',
    'referred_user_amount_hint' => 'Фиксированная сумма будет начислена привлеченному пользователю, когда пользователь зарегистрируется, используя партнерский код.',
  	'referral_description_hint' => 'Описание будет отображено на панели пользователя.',
  	'total_user_hint' => 'Общее количество Привлеченных Пользователей',
  	'total_user_desc' => 'Пользователи, зарегистрировавшиеся на платформе с использованием реферального кода.',
  	'total_affiliate_hint' => 'Общее количество Пользователей-Партнеров',
  	'total_affiliate_desc' => 'Пользователи, которые направили хотя бы одного пользователя на платформу, используя свой реферальный код.',
  	'total_aff_amount_hint' => 'Общая Сумма Регистрации',
  	'total_aff_amount_desc' => 'Сумма, заработанная как реферальными пользователями, так и аффилированными пользователями в качестве регистрационного бонуса.',
  	'total_aff_commission_hint' => 'Общая партнерская комиссия',
  	'total_aff_commission_desc' => 'Сумма, заработанная аффилированными пользователями в качестве комиссии за продажу.',
  	'aff_sales_commission_hint' => 'Комиссия за продажу',
  	'aff_sales_commission_desc' => 'Сумма, заработанная пользователем в качестве комиссии за продажу. Каждая продажа, совершенная пользователями нижнего уровня, будет включать комиссию для аффилированного пользователя.',
  	'registration_income_hint' => 'Регистрационный доход',
  	'registration_income_desc' => 'Сумма, заработанная пользователем в качестве регистрационного бонуса. Когда пользователь регистрируется с использованием партнерского кода и активирует свою учетную запись, эта сумма будет calculated.me',
    'active_referral_hint' => 'Поля ввода реферала и связанные с ними финансовые процессы будут активированы.',
  	'active_referral_new_users_hint' => 'Активировав этот переключатель, партнерская функция будет активирована для новой регистрации по умолчанию.',
  
    'multi_language_content' => 'Многоязычный контент',
  	'multi_language_content_hint' => 'Вы сможете определять содержимое платформы на разных языках. Если отключить его, выпадающий список языков будет скрыт.',
  
    'no_chapter' => 'Нет Раздела',
    'class_url' => 'URL-адрес курса',
    'class_url_hint' => 'URL-адрес курса должен быть уникальным, используйте его без пробелов. Он будет сгенерирован по умолчанию; вы можете использовать значение по умолчанию.',
    'page_background' => 'Фоны страниц',
  	'home_video_or_image_box' => 'Раздел Видео/Изображений',
	'rtl' => 'Включить арабские символы',
	'content_translate' => 'Перевод контента',	
    'posted_notifications' => 'Опубликованные уведомления',	
    'posted' => 'Опубликованный',
	'select_a_partner_hint' => 'Инструктор-партнер будет иметь доступ к содержимому курса, и его профиль будет отображаться на странице курса.',
	'search_instructor' => 'Поиск инструктора',	
    'search_student' => 'Поиск студента',	
    'search_users' => 'Поиск пользователей',
	'session' => 'Живая сессия',
	'text_lesson' => 'Текстовый урок',
  	'balances' => 'Балансы',
];