<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Panel
    |--------------------------------------------------------------------------
    */

    'new_users' => 'Новые пользователи',
    'user' => 'Пользователь',
    'users' => 'Пользователи',


    'followers' => 'Последователи',
    'following' => 'Following',
    'follow' => 'Cледовать',
    'unfollow' => 'Не следовать',



    'webinars' => 'Курсы',
    'webinar' => 'Курс',
    'webinar_sales' => 'Продажи в прямом эфире',
    'content_sales' => 'Продажи курсов',
    'my_webinars' => 'Мои курсы',
    'you_not_have_any_webinar' => 'Нет курса!',
    'no_result_hint' => 'Создайте свой первый курс и позвольте другим обучаться.',
    'choose_webinar' => 'Выберите курс',
    'certificates' => 'Сертификаты',
    'quizzes' => 'Викторины',
    'financial' => 'Финансирования',
    'requests' => 'Запросы',
    'support' => 'Поддержка',
    'send_new_support' => 'Новое сообщение службы поддержки',
    'notifications' => 'Уведомления',
    'settings' => 'Настройки',
    'log_out' => 'Выйти ',
    'create_a_class' => 'Создайте курс',
    'create_a_webinar' => 'Создайте курс',

    'invited_classes' => 'Приглашение на курсы',
    'invited_teacher' => 'Приглашение учителю',
    'invited_by' => 'Приглашение',
    'classes' => 'Курсы',
    'my_classes' => 'Мои курсы',
    'my_activity' => 'Моя деятельность',
    'download_sales' => 'Скачать Продажи',
    'course_sales' => 'Продажи курсов',
    'only_not_conducted_webinars' => 'Только онлайн занятия',
    'conducted' => 'Проведенный',
    'not_conducted' => 'Не проводилось',

    'upcoming' => 'Предстоящий',
    'start_learning' => 'Начните учиться',
    'my_purchases_no_result' => 'Нет Купленного Курса!',
    'my_purchases_no_result_hint' => 'Начните учиться у лучших инструкторов и наслаждайтесь...',

    'comment' => 'Комментарий',
    'comments' => 'Комментарии',
    'reply' => 'Ответить',
    'replied' => 'Ответил',
    'not_replied' => 'Не ответил',
    'report' => 'Отчет',
    'report_success' => 'Ваш отчет был отправлен.',
    'report_fail' => 'Отчет не удался. Убедитесь, что вы вошли в систему.',
    'new_comments' => 'Новые комментарии',
    'my_class_comments' => 'Комментарии к моему курсу',
    'my_comments' => 'Мои комментарии',
    'comments_statistics' => 'Статистика комментариев',
    'filter_comments' => 'Фильтр комментариев',
    'webinar_comments_list' => 'Список комментариев к курсу',
    'comments_no_result' => 'У вас нет комментариев!',
    'comments_no_result_hint' => "Когда прокомментируют ваши курсы, они появятся в этом списке.",
    'my_comments_no_result' => 'Вы не оставляли комментариев!',
    'my_comments_no_result_hint' => "Ваши комментарии помогут улучшить качество сообщества...",

    'my_purchases' => 'Мои покупки',
    'no_result_purchases' => 'Нет Купленного Курса!',
    'no_result_purchases_hint' => 'Начните учиться у лучших инструкторов и наслаждайтесь...',
    'purchase_date' => 'Дата Покупки',
    'purchased' => 'Приобретенные курсы',

    'favorites' => 'Избранные',
    'favorite' => 'Избранное',
    'favorite_live_classes' => 'Избранные курсы',
    'no_result_favorites' => 'Нет Избранныч курсов!',
    'no_result_favorites_hint' => 'Вы можете добавить курс в избранные и позже записаться на него.',

    'meeting' => 'Встреча',
    'meetings' => 'Встречи',
    'open_meetings' => 'Открытые встречи',
    'pending_appointments' => 'Предстоящие встречи',
    'total_meetings' => 'Общее количество встреч',
    'amount' => 'Объем',
    'sales' => 'Продажи',
    'sales_amount' => 'Объем продаж',
    'active_hours' => 'Активные часы',
    'meeting_statistics' => 'Статистика встреч',
    'filter_meetings' => 'Фильтр встреч',
    'meeting_list' => 'Список встреч',
    'meeting_requests_list' => 'Список запросов на встречу',
    'show_only_open_meetings' => 'Показывать только открытые собрания',
    'create_link' => 'Создать ссылку',
    'contact_student' => 'Контакты студента',
    'contact_instructor' => 'Контакты учителя',
    'finish_meeting' => 'Окончить встречу',
    'meeting_no_result' => 'Нет запросов на встречу!',
    'meeting_no_result_hint' => 'Зарезервированные встречи будут отображаться в этом списке.',
    'student_contact_information' => 'Контактная информация студента',
    'instructor_contact_information' => 'Контактная информация учителя',
    'my_timesheet' => 'Мое расписание',
    'saturday' => 'Суббота',
    'sunday' => 'Воскресенье',
    'monday' => 'Понедельник',
    'tuesday' => 'Вторник',
    'wednesday' => 'Среда',
    'thursday' => 'Четверг',
    'friday' => 'Пятница',
    'join_live_meeting' => 'Присоединится к встрече',
    'add_live_meeting_link' => 'Добавить ссылку к встрече',
    'add_live_meeting_link_success' => 'Ссылка к встрече успешно добавлена',
    'add_live_meeting_link_fail' => 'Ошибка при добавлении ссылки к встрече',
    'add_live_meeting_link_hint' => 'Вы можете использовать ссылки Zoom, Bigbluebutton и т.д.',
    'url' => 'URL-адрес',
    'my_hourly_charge' => 'Почасовая оплата',
    'number_only' => 'Только цифры...',
    'temporary_disable_meetings' => 'Временное отключение встречи',
    'success_temporary_disable_meetings' => 'Встреча успешно окончена.',
    'error_temporary_disable_meetings' => 'Не удалось отключить встречу.',
    'discount' => 'Ставка дисконтирования',

    // dashboard
    'dashboard' => 'Панель',
    'i_not_available' => 'Активировать автономный статус',
    'hi' => 'Привет',
    'have_event' => 'У вас есть :подсчитайте новые события',
    'view_all_events' => 'Просмотр всех событий',
    'account_balance' => 'Баланс счета',
    'with_drawable' => 'Выводимый',
    'live_requests' => 'Запросы на встречи',
    'monthly_sales' => 'Ежемесячные Продажи',
    'learning_statistics' => 'Статистика обучения',
    'support_messages' => 'Сообщения поддержки',
    'next_badge' => 'Следующий Значок',
    'noticeboard' => 'Доска объявлений',
    'noticeboards' => 'Уведомления',
    'not_verified_alert' => 'Ваша личность и финансовая информация не проверены, поэтому это может привести к задержке в процессе выплаты. Пожалуйста, определите их из',
    'this_link' => 'Настройки',


    // Conversations
    'conversations' => 'Разговоры',
    'create_support_message' => 'Новое сообщение службы поддержки',
    'course_support' => 'Поддержка курса',
    'course_type' => 'Тип курса',
    'platform_support' => 'Поддержка платформы',
    'department' => 'Отдел',
    'attach' => 'Привязанность',
    'attach_file' => 'Прикрепить файл',
    'open_conversations' => 'Открытые разговоры',
    'closed_conversations' => 'Закрытые разговоры',
    'total_conversations' => 'Всего разговоров',
    'messages_history' => 'История сообщений',
    'support_summary' => 'Резюме поддержки',
  	'classes_support' => 'Поддержка курсов',
  	'support_tickets' => 'Билеты',
    'staff' => 'Персонал',
    'teacher' => 'Учитель',
    'open' => 'Открыть',
    'closed' => 'Закрытый',
    'close_request' => 'Запрос на закрытие',
    'reply_to_the_conversation' => 'Ответ на беседу',
    'support_no_result' => 'У вас нет сообщений поддержки',
    'support_no_result_hint' => 'Вы можете связаться с инструкторами и службой поддержки платформы.',

    'select_support' => 'Выберите беседу',
    'select_support_hint' => 'Пожалуйста, выберите разговор со службой поддержки, чтобы отобразить историю сообщений.',
    'message_filters' => 'Фильтр сообщении',

    // notifications
    'notification_no_result' => 'Никаких уведомлений.',
    'notification_no_result_hint' => 'Каждое важное событие будет замечено вами...',

    // comments
    'show_only_new_comments' => 'Показывать только новые комментарии',
    'reply_to_the_comment' => 'Ответ на комментарий',
    'edit_comment' => 'Редактировать комментарий',

    //Marketing
    'marketing' => 'Маркетинг',
    'discounts' => 'Скидки',
    'create_a_new_discount' => 'Скидка на новый курс',
    'create_a_new_special_offer' => 'Создайте новое специальное предложение',
    'show_only_active_discounts' => 'Показывать только активные скидки',
    'discount_no_result' => 'Скидка не предоставляется...',
    'discount_no_result_hint' => 'Вы можете создавать скидки и увеличивать свои продажи.',
    'special_offers_no_result' => 'Никаких Скидок...',
    'special_offers_no_result_hint' => 'Вы можете добавить скидку к своим курсам и увеличить свои продажи.',

    'promotion' => 'Продвижение',
    'promotions' => 'Акции',
    'select_promotion_plan' => 'Выберите план продвижения',
    'promotions_history' => 'История рекламных акций',
    'promotion_days' => 'Для :дневных дней',
    'select_course' => 'Выберите курс',
    'show_only_active_promotions' => 'Показывать только активные рекламные акции',
    'popular' => 'ПопулярныйПопулярный',
    'plan' => 'План',
    'pay' => 'Оплатить',
    'expired' => 'Истекший',
    'promote_the_webinar' => 'Продвигать курс',
    'select_webinar_for_promotion' => 'Пожалуйста, выберите курс, который вы хотите продвигать.',
    'promotion_no_result' => 'Никакого Продвижения !',
    'promotion_no_result_hint' => 'Активируя планы продвижения, вы можете увеличить количество просмотров ваших курсов и продаж.',

    // Instructors
    'filter_instructors' => 'Фильтровать инструкторов',
    'instructors_list' => 'Список инструкторов',
    'add_an_instructor' => 'Новый учитель',
    'instructors_no_result' => 'Учитель еще не добавлен!',
    'instructors_no_result_hint' => 'Вы можете создавать учителей, связанных с организацией.',

    'filter_students' => 'Фильтровать учеников',
    'students_list' => 'Список учеников',
    'add_an_student' => 'Новый ученик',
    'students_no_result' => 'Ученик еще не добавлен!',
    'students_no_result_hint' => 'Вы можете легко добавлять учеников своей организации.',

    'meeting_sales' => 'Продажи на встречах',
    'appointment_sales' => 'Продажи на встречах',

    'bio' => 'Биография',
    'job_title' => 'Должность',
    'bio_hint_1' => '"Должность" будет отображаться внизу вашего имени в карточках профиля.',
    'bio_hint_2' => 'Будьте кратки (2 или 3 слова), например, "Разработчик продукта, старший инженер-программист".',
    'interests_hint_1' => 'Выбор интересующих тем (для преподавателей) поможет студентам найти вас для живых встреч.',
    'interests_hint_2' => 'Если вы проводите живые встречи, выбирая более точные предлагаемые темы.',
    'not_assign_any_webinar' => 'Не приписан ни к какому курсу',
    'active' => 'Активный',
    'inactive' => 'Неактивный',
    'name' => 'Имя',
    'special_offers' => 'Специальные предложения',
    'special_offer' => 'Специальное предложение',
    'show_only_active_special_offers' => 'Показывать Только Активные Специальные Предложения',

    'offline_title' => 'Активировать автономный статус',
    'offline_message' => 'Автономное сообщение',
    'offline_success' => 'Ваш статус успешно изменен!',
    'offline_hint' => 'Если вы переведете свою учетную запись в автономный режим, в вашем профиле появится сообщение, и оно будет замечено пользователями. Вы можете ввести персонализированное сообщение в следующем поле ввода.',

    // months
    'month_1' => 'Январь ',
    'month_2' => 'Февраль ',
    'month_3' => 'Март ',
    'month_4' => 'Апрель ',
    'month_5' => 'Май ',
    'month_6' => 'Июнь ',
    'month_7' => 'Июль ',
    'month_8' => 'Август ',
    'month_9' => 'Сентябрь ',
    'month_10' => 'Октябрь ',
    'month_11' => 'Ноябрь ',
    'month_12' => 'Декабрь ',

    'user_setting_success' => 'Ваша информация успешно обновлена',

    'remaining' => 'Оставшийся',

    'organization_classes' => 'Организационные курсы',
    'filter_classes' => 'Фильтровать курсы',
    'only_not_free_classes' => 'Только платные курсы',
    'only_free_classes' => 'Только бесплатные курсы',

    'new_noticeboard' => 'Новое уведомление',
    'noticeboard_success_send' => 'Новое уведомление успешно отправлено',
    'noticeboard_success_send_to' => 'Новая доска объявлений успешно отправлена для :users_count',

    'more_info' => 'Дополнительная информация',
  	'partner_instructor_hint' => 'Преподаватель-партнер будет иметь доступ к содержимому курса, и его профиль будет отображаться на странице курса.',
  	
  	'affiliate' => 'Филиал',
    'affiliates' => 'Филиал',
    'affiliates_page' => 'Партнерский маркетинг',
    'affiliate_statistics' => 'Партнерская статистика',
    'affiliate_summary' => 'Резюме партнера',
    'earnings' => 'Прибыль',
    'referred_users' => 'Привлеченные Пользователи',
    'registration_bonus' => 'Бонус за регистрацию',
    'affiliate_bonus' => 'Комиссия за продажу',
    'registration_date' => 'Дата регистрации',
    'user_registration_reward' => 'Ваш доход от регистрации каждого привлеченного пользователя',
    'referred_user_purchase_commission' => 'Ваша комиссия от покупок привлеченных пользователей',
    'referred_user_registration_reward' => 'Доход привлеченного пользователя при регистрации с вашим партнерским кодом',
    'your_affiliate_code' => 'Ваш партнерский код',
    'affiliate_url' => 'Ваш партнерский URL-адрес',
	'content_defined' => 'Содержание Определено',
  	'purchased_courses' => 'Приобретенные Курсы',
];
