<?php

return [

    /*
    |--------------------------------------------------------------------------
    | General Translations
    |--------------------------------------------------------------------------
    */

    'title' => 'Загаловок',
    'sub_title' => 'Подзаголовок',
    'name' => 'Имя',
    'seo_description' => 'SEO-Мета-описание',
    'cover_image' => 'Изображение на Обложке',
    'thumbnail_image' => 'Уменьшенное изображение',
    'image' => 'Изображение',
  	'images' => 'Изображения',
    'demo_video' => 'Демонстрационное видео',
    'optional' => 'Необязательный',
    'description' => 'Описание',
    'summary' => 'Резюме',
    'study_time' => 'Учебное время',
    'date_time' => 'Дата/Время',
    'availability_times' => 'Время доступности',
    'available' => 'Доступный',
    'available_for_meetings' => 'Доступен для проведения совещаний',
    'meeting' => 'Встреча',
    'meetings' => 'Встречи',
    'link' => 'Ссылка',
    'duration' => 'Продолжительность',
    'minutes' => 'Минут',
    'min' => 'Минута',
    'view' => 'Смотреть',
    'view_profile' => 'Просмотр профиля',
    'review_or_edit' => 'Обзор/Редактирование',
    'review' => 'Обзор',
    'invited' => 'Приглашенный',
    'try_again' => 'Пробовать снова',
    'you_can_try_again' => 'Не волнуйся, ты можешь попробовать еще раз.',
    'start' => 'Начать',
    'volume' => 'Объем',
    'file_type' => 'Тип файла',
    'accessibility' => 'Доступность',
    'choose_accessibility' => 'Бесплатно или платно?',
    'attachments' => 'Вложения',
    'choose_attachments' => 'Выберите связанные файлы в качестве вложений к уроку',
    'paid' => 'Оплачено',
    'paid_amount' => 'Выплаченная Сумма',
    'instructor' => 'Инструктор',
    'instructors' => 'Инструкторы',
    'students' => 'Ученики',
    'students_and_instructors' => 'Студенты и преподаватели',
    'search_instructors' => 'Поиск Инструкторов...',
    'publish_date' => 'Дата Публикации',
    'forced' => 'Принудительный',
    'yes' => 'Да',
    'no' => 'Нет',

    'course_sessions' => 'Занятия в классе',
    'previous_lesson' => 'Предыдущий Урок',
    'next_lesson' => 'Следующий Урок',

    'drag_to_change_order' => 'Перетащите, чтобы изменить порядок',

    'controls' => 'Действия',
    'phone' => 'Телефон',
    'mobile' => 'Телефон',
    'email' => 'Электронная почта',

    'add_time' => 'Добавить Время',
    'clear_all' => 'Очистить Все',
    'additional_information' => 'Дополнительная информация',
    'capacity' => 'Вместимость',
    'start_date' => 'Start Date',
    'time' => 'Время',
    'date' => 'Дата',
    'date_created' => 'Дата Создания',
    'partner_instructor' => 'Партнер-инструктор',
    'subscribe' => 'Подписываться',
    'add_to_cart' => 'Добавить в корзину',
    'add_to_calendar' => 'Добавить в календарь',
    'add_to' => 'Добавить к',
    'reminder' => 'Напоминание',
    'calendar' => 'Календарь',
    'price' => 'Цена',
    '0_for_free' => 'Введите 0 бесплатно',
    'free' => 'Бесплатно',
    'enroll_on_webinar' => 'Записаться на курс',
    'free_meetings' => 'Бесплатные Встречи',
    'select_a_partner_teacher' => 'Выберите партнера-инструктора',
    'select_a_teacher' => 'Выберите учителя',
    'choose_instructor' => 'Выберите учителя',
    'search' => 'Поиск',
    'search_instructor' => 'Поиск имени преподавателя, адреса электронной почты или телефона',
    'search_user' => 'Поиск пользователя',
    'tags' => 'Теги',
    'type_tag_name_and_press_enter' => 'Введите название тега и нажмите enter',
    'moderator_password' => 'Пароль Модератора',

    'category' => 'Категория',
    'choose_category' => 'Выберите категорию',
    'category_filters' => 'Фильтры категорий',
    'tickets' => 'Билеты',
    'add_ticket' => 'Новый Тарифный План',
    'add_plan' => 'Новый План',
    'add_new_ticket' => 'Новый Тарифный План',
    'discount' => 'Скидка',
    'ticket_no_result' => 'Нет тарифного плана!',
    'ticket_no_result_hint' => 'Создавая тарифные планы, вы можете добавлять цены на свой курс в зависимости от времени и вместимости.',

    'edit' => 'Редактировать',
    'delete' => 'Удалить',
    'remove' => 'Удалять',

    'list' => 'Список',
    'reservation' => 'Бронирование',
    'my_reservation' => 'Мои оговорки',
    'result' => 'Результат',
    'results' => 'Результаты',
    'my_results' => 'Мои результаты',

    'all' => 'Все',
    'sessions' => 'Сессий',
    'add_session' => 'Новая сессия',
    'add_new_sessions' => 'Новая Живая Сессия',
    'sessions_no_result' => 'Никаких живых сессий!',
    'sessions_no_result_hint' => 'Вы можете создавать живые сеансы, чтобы учащиеся могли присоединиться и начать обучение.',
    'create_join_link' => 'Создать ссылку для присоединения',

    'newest' => 'Новейший',
    'expensive' => 'Самая Высокая Цена',
    'inexpensive' => 'Самая Низкая Цена',
    'bestsellers' => 'Бестселлеры',
    'best_rates' => 'Лучший рейтинг',

    'files' => 'Файлы',
    'file' => 'Файл',
    'source' => 'Источник',
    'add_files' => 'Новый файл',
    'add_new_files' => 'Добавить новый файл',
    'files_no_result' => 'Файл не определен!',
    'files_no_result_hint' => 'Вы можете определить видеозаписи курса, проекты, вложения и упражнения в виде файлов.',

    'test_lesson' => 'Текстовый урок',
    'lesson' => 'Урок',
    'add_test_lesson' => 'Новый текстовый урок',
    'add_new_test_lesson' => 'Добавить новый текстовый урок',
    'text_lesson_no_result' => 'Никакого текстового урока!',
    'text_lesson_no_result_hint' => 'Создавайте текстовые уроки, чтобы учащиеся могли записаться на них и начать обучение.',

    'prerequisites' => 'Предпосылки',
    'add_prerequisites' => 'Новое Предварительное условие',
    'add_new_prerequisites' => 'Добавить новое предварительное условие',
    'select_prerequisites' => 'Выберите Необходимое условие',
    'search_prerequisites' => 'Поиск необходимых условий',
    'prerequisites_no_result' => 'Никаких предварительных условий не определено!',
    'prerequisites_no_result_hint' => 'Вы можете создать принудительные или предлагаемые предварительные условия, чтобы учащиеся могли лучше учиться.',

    'basic_information' => 'Основная информация',
    'extra_information' => 'Дополнительная Информация',
    'pricing' => 'Ценообразование',
    'content' => 'Содержание',

    'faq' => 'Часто задаваемые вопросы',
    'add_faq' => 'Новые часто задаваемые вопросы',
    'answer' => 'Ответ',
    'answers' => 'Ответы',
    'view_answers' => 'Просмотр ответов',
    'faq_no_result' => 'Часто задаваемые вопросы не определены!',
    'faq_no_result_hint' => 'Создавая часто задаваемые вопросы, вы поможете пользователям узнать больше о вашем курсе.',

    'quiz_certificate' => 'Тест и сертификация',
    'certificate' => 'Сертификат',
    'certificate_id' => 'Идентификатор сертификата',
    'certificate_and_documents' => 'Сертификаты и документы',
    'add_quiz' => 'Новая Викторина',
    'add_new_quizzes' => 'Новая Викторина',
    'select_a_quiz' => 'Выберите тест',
    'quiz' => 'Квиз',
    'questions' => 'Вопросы',
    'total_mark' => 'Общая Оценка',
    'pass_mark' => 'Проходной балл',
    'mark' => 'Марк',
    'not_participated' => 'Не Участвовал',
    'dont_have_quiz' => 'У вас нет теста, пожалуйста, определите тест.',
    'quizzes_no_result' => 'Для этого курса тест не выбирается.',
    'quizzes_no_result_hint' => 'Создавая тесты, вы можете оценивать студентов и вручать им сертификаты.Создавая тесты, вы можете оценивать студентов и вручать им сертификаты.',

    'agree_rules' => 'Я согласен с условиями и правилами.',

    'message_to_reviewer' => 'Сообщение рецензенту',

    'send_for_review' => 'Отправить на рассмотрение',
    'save_as_draft' => 'Сохранить как черновик',
    'draft' => 'Черновик',
    'waiting' => 'Ожидание',
    'done' => 'Сделано',
    'reject' => 'Отклонять',
    'rejected' => 'Отклоненный',

    'close' => 'Закрывать',
    'save' => 'Сохранить',
    'continue' => 'Продолжать',
    'submit' => 'Сохранить',
    'new' => 'Новое',
    'history' => 'История',
    'item_id' => 'Идентификатор элемента',
    'export_list' => 'Экспорт списка учащихся',
    'duplicate' => 'Дубликат',

    'updated_at' => 'Дата Обновления',
    'from' => 'От',
    'to' => 'К',
    'show_results' => 'Показывать результаты',
    'status' => 'Статус',
    'published' => 'Опубликованный',
    'type' => 'Тип',
    'active' => 'Активный',
    'verified' => 'Проверенный',
    'not_verified' => 'Не проверено',
    'inactive' => 'Неактивный',
    'disabled' => 'Нетрудоспособный',
    'disable' => 'Отключать',
    'open' => 'Открыть',
    'invoice' => 'Счет-фактура',
    'feedback' => 'Обратная связь',
    'by' => 'Около',
    'finish' => 'Заканчивать',
    'finished' => 'Законченный',
    'pending' => 'Ожидаемый',
    'selected' => 'Выбранный',
    'select' => 'Выбрать',
    'required' => 'Требуемый',
    'not_bought' => 'Не Куплен!',
    'not_access' => 'Доступ запрещен!',
    'not_access_to_this_content' => 'У вас нет доступа к этому контенту!',
    'play' => 'Играть',
    'play_online' => 'Воспроизведение (трансляция)',
    'read' => 'Прочитай',

    'are_you_sure' => 'Ты уверен?',
    'deleteAlertHint' => "Это действие не может быть отменено!",
    'deleteAlertConfirm' => 'Удалить',
    'deleteAlertFailHint' => 'Ошибка при удалении элемента!',
    'deleteAlertSuccessHint' => 'Элемент успешно удален.',
    'cancel' => 'Отменить',
    'canceled' => 'Отмененный',
    'success' => 'Успех',
    'fail' => 'Провал',

    'unavailable' => 'Недоступный',
    'unavailable_description' => 'Сообщение о недоступности',

    'not_defined' => 'Не определен',

    'days' => 'Дни',
    'day' => 'День',
    'hr' => 'Эйчар',
    'sec' => 'Сек',
    'off' => 'Прочь',
    'offer' => ':скидка% от предложения',

    'sort_by' => 'Сортировать по',
    'in' => 'В',
    'created_by' => 'Созданный',
    'created_at' => 'Дата Создания',
    'created' => 'Созданный',
    'create' => 'Создавать',
    'save_change' => 'Сохранить',
    'ratings' => 'Рейтинги',

    'share' => 'Делиться',
    'share_this_course_with_others' => 'Поделитесь курсом со своими друзьями',
    'profile' => 'Профиль',
    'telegram' => 'Telegram',
    'facebook' => 'Facebook',
    'whatsapp' => 'Whatsapp',
    'twitter' => 'Twitter',
    'book_a_meeting' => 'Запишитесь на встречу',
    'author_posts' => 'Авторские Сообщения',
    'reserve_a_meeting' => 'Зарезервируйте встречу',
    'go_to_class' => 'Перейти к курсу',
    'go_to_settings' => 'Перейдите в Настройки',
    'course_page_title' => 'Курс',

    'duplicate_review_for_webinar' => 'Дублирующий отзыв для курса',
    'creator' => 'Создатель',
    'manual' => 'Инструкция',
    'automatic' => 'Автоматический',
    'start_payment' => 'Начальный платеж',
    'pay' => 'Оплатить',
    'saturday' => 'Суббота',
    'sunday' => 'Воскресенье',
    'monday' => 'Понедельник',
    'tuesday' => 'Вторник',
    'wednesday' => 'Среда',
    'thursday' => 'Четверг',
    'friday' => 'Пятница',
    'all_days' => 'Все Дни',

    'my_panel' => 'Моя панель',
    'my_profile' => 'Мой Профиль',
    'user_profille_page_title' => 'Профиль пользователя',
    'edit_selected_image' => 'Обрезать выбранное изображение',

    'request_failed' => 'Запрос Не выполнен',
    'request_success' => 'Запрос выполнен успешно!',

    'cart_page_title' => 'Тележка',
    'checkout_page_title' => 'Проверка',
    'channel_payment_disabled' => 'Платежный шлюз отключен.',
    'income_los_then_minimum_payout' => 'Ваш доход меньше минимальной суммы выплаты. Пожалуйста, подождите, чтобы пройти ограничение.',

    'paid_form_online_payment' => 'Онлайн-Оплата',
    'paid_form_credit' => 'Оплаченный кредит в форме',
    'paid_for_sale' => 'Оплачено для продажи',
    'tax_get_form_buyer' => 'Налоговая форма Покупателя',
    'income_sale' => 'Доход От Продажи',
    'paid_for_commission' => 'Оплаченная комиссия',
    'get_commission_from_seller' => 'Комиссия от Продавца',
    'refund_money_to_buyer' => 'Возвращается покупателю',
    'refund_tax' => 'Возвращенный Налог',
    'refund_commission_to_seller' => 'Возвращенная комиссия Продавцу',
    'refund_commission' => 'Возвращенная Комиссия',
    'refund_income' => 'Возвращенный Доход',
    'charge_account' => 'Платежный счет',
    'withdraw_account' => 'Вывести средства со счета',
    'income_for_subscribe' => 'Доход за подписку',
    'paid_form_subscribe' => 'Оплаченная подписка',
    'income_for_promotion' => 'Оплачено продвижение по службе',

    'ticket_for_students_until_date' => 'Для первых :студенты студенты до :дата',
    'ticket_until_date' => 'до :дата',

    'about' => 'О',
    'educations' => 'Образование',
    'experiences' => 'Опыт',
    'occupations' => 'Темы навыков',
    'identity_and_financial' => 'Идентификация и финансовые',

    'copy' => 'Копировать',
    'copied' => 'Скопированный',
    'user_role' => 'Тип пользователя',
    'all_roles' => 'Все Типы',

    'error_404_page_title' => 'Страница не найдена',
    'i_passed_this_lesson' => 'Я прошел этот урок',
    'course_learning_change_status_success' => 'Ваш статус обучения успешно изменен.',
    'course_learning_change_status_error' => 'Не удалось изменить статус обучения.',
    'course_learning_passed' => ': процент% пройденного курса.',

    'not_login_toast_lang' => 'Ограниченный контент',
    'not_login_toast_msg_lang' => 'Пожалуйста, войдите в систему, чтобы получить доступ к контенту.',
    'not_access_toast_lang' => 'Доступ запрещен',
    'not_access_toast_msg_lang' => 'У вас нет доступа к этому контенту.',
    'can_not_try_again_quiz_toast_lang' => 'Протянул руку',
    'can_not_try_again_quiz_toast_msg_lang' => 'Вы не можете пройти этот тест снова.',
    'can_not_download_certificate_toast_lang' => 'Загрузка не удалась',
    'can_not_download_certificate_toast_msg_lang' => 'Вы не можете загрузить этот сертификат.',
    'session_finished_toast_title_lang' => 'Сеанс Завершен',
    'session_finished_toast_msg_lang' => 'Вы опоздали, сеанс закончен.',

    'zoom_api' => 'API масштабирования',
    'zoom_jwt_token' => 'Увеличить токен JWT',
 	'how_zoom_jwt_token' => 'Как создать токен Zoom JWT',
    'instructor_is_not_available' => 'Инструктор временно недоступен.',
  
    'chapter' => 'Раздел',
    'chapters' => 'Разделы',
    'add_new_chapter' => 'Добавить Новый Раздел',
    'new_chapter' => 'Новый Раздел',
    'edit_chapter' => 'Раздел редактирования',
    'chapter_title' => 'Название раздела',
    'topic' => 'Тема',
    'parts' => 'Части',
  	'content_defined' => 'Содержание Определено',
    'no_chapter' => 'Нет Раздела',
  	'add_file' => 'Добавить файл',
];
